### ISSUE TITLE
Suggestion: Add hint on repo landing page that this is not supposed to be browsed directly on Github

### ISSUE THREAD

**Issue by xanoni** [zkSNACKs/WasabiDoc#1000]
Suggestion: Add a hint on the repository landing page (https://github.com/zkSNACKs/WasabiDoc/blob/master/README.md) to tell visitors that these docs are not supposed to be browsed directly on Github, given that relative links are broken.

See: https://github.com/zkSNACKs/WasabiDoc/issues/877

**Comment by MarnixCroes** [comment]
For me this works now.
Please comment if it doesn't for you.
