### ISSUE TITLE
Client is stuck on connecting with 0 peers when kill-switch is turned on on proton vpn for apple silicon

### ISSUE THREAD

**Issue by VAM88** [zkSNACKs/WasabiDoc#1039]
As title, client works without VPN, now even with VPN, however cannot run the kill-switch at the same time since it makes wasabi wallet stuck on connecting and 0 peers after backend and tor is connected. Why is this?

**Comment by BTCparadigm** [comment]
Could be something in the configurations or that using this VPN + Tor takes too long to get messages through in time.

**Comment by yahiheb** [comment]
@VAM88  As a side note, this the documentation repository, and thus Wasabi Wallet related issues should be open here https://github.com/zkSNACKs/WalletWasabi/discussions/categories/support
