### ISSUE TITLE
Please state clearly in your docs that over .1 BTC is required to use the coinjoin function

### ISSUE THREAD

**Issue by jjames2** [zkSNACKs/WasabiDoc#1062]
Hi, downloaded wasabi wallet but when I tried to use the coinjoin functionality it required well more BTC to queue than I was intending to send. Please state clearly that this feature can only be used for mid/large size transactions over .1.

**Comment by yahiheb** [comment]
This is mentioned already in the documentation:

https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-are-the-equal-denominations-created-in-one-mixing-round
https://docs.wasabiwallet.io/using-wasabi/CoinJoin.html
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#why-aren-t-there-smaller-equal-denomination-outputs-like-0-05-btc
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#how-can-i-mix-large-amounts

Having said that a [Testnet Version for Wasabi Wallet 2.0 has been released](https://twitter.com/wasabiwallet/status/1498762641812172807), and it does not have this 0.1 btc minimum required to coinjoin.

**Comment by yahiheb** [comment]
This was answered.
