### ISSUE TITLE
wasabi crashing

### ISSUE THREAD

**Issue by rsj3** [zkSNACKs/WasabiDoc#1063]
immediate crash 

exception info:
no more byte to read

please help

**Comment by MarnixCroes** [comment]
@rsj3 
Hi,

Oh that sucks.
This should fix it:

The file that contains the addresses of peers discovered over the time is corrupted in your file system. That file is just a cache used to speed up the discovery of new peers and it is safe to delete it.
The file is located in [Wasabi wallet data folder]/client/AddressManager/AddressManagerMain.dat 

So, close wasabi. Delete that corrupted file and start wasabi again. It can take a while to discover new peers but it will find them and recreate that file again.
Here is where you can find the Wasabi Wallet Data Folder:
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#where-can-i-find-the-wasabi-data-folder



Let us know if you need more help!

**Comment by yahiheb** [comment]
@rsj3 What @MarnixCroes mentioned above should fix your issue.

FTR this is the Wasabi documentation repository, so if you need any support you should open a [discussion](https://github.com/zkSNACKs/WalletWasabi/discussions/categories/support) or an [issue](https://github.com/zkSNACKs/WalletWasabi/issues/new/choose) in the main repository https://github.com/zkSNACKs/WalletWasabi

Closing this.
