### ISSUE TITLE
Using Trezor with Wasabi

### ISSUE THREAD

**Issue by DLux76198** [zkSNACKs/WasabiDoc#1064]
When I plug my Trezor into Wasabi, it only displays one of my accounts. A Trezor is capable of holding multiple accounts. For some reason, only one account is shown. Is there a fix for this?

**Comment by yahiheb** [comment]
Wasabi monitors only one account, on main net it is the path `m/84'/0'/0'`.

> Is there a fix for this?

Currently there is not.

FTR this is the Wasabi documentation repository, so if you need any support you should open a [discussion](https://github.com/zkSNACKs/WalletWasabi/discussions/categories/support) or an [issue](https://github.com/zkSNACKs/WalletWasabi/issues/new/choose) in the main repository https://github.com/zkSNACKs/WalletWasabi

Closing this.
