### ISSUE TITLE
Recover wallet error message

### ISSUE THREAD

**Issue by Caerus57** [zkSNACKs/WasabiDoc#1073]
Hello, I am trying to recover a wallet and receive this error message

Error!
FormatException: Word form is not in the wordlist for this language, cannot continue to rebuild entropy from wordlist

Kali Linux
Kali GNU/Linux Rolling
Release:        2022.1

**Comment by yahiheb** [comment]
This means you are using a wrong word that is not part of the wordlist used to get your recovery words.

Make sure to check your recovery words again.

**Comment by Caerus57** [comment]
Thank you for the response.  Just to double check.  Each of the words I use comes up as a "suggestion" is this still the case?
Thanks again

**Comment by yahiheb** [comment]
> Just to double check. Each of the words I use comes up as a "suggestion" is this still the case?

Yes
