### ISSUE TITLE
How long does it take to synchronize transactions?

### ISSUE THREAD

**Issue by Dankra30** [zkSNACKs/WasabiDoc#1078]
I recently installed Wasabi Wallet und wanted to try it out by receiving bitcoins to my first address. Now I started the Wallet on Windows 11 and it started synchronizing and 15 minutes later is still synchronizing. It doesn't show, that the transaction was received and now I'm worried, that I just lost money because of a problem it probably has. Could you tell me, if it's normal for it synchronizing that long? Is it a one time thing or is this something I will have problems with everytime I start it?

One thing I probably should also mention is that it shows me downloading about 160k filters, which I don't know what they are. It's version 1.1.13.1 btw.

Thank you for your time and have a nice day!

Kind regards,
Dankra

Update: 
I've started the Wallet multiple times over the day as of now and after crashing everytime I boot it up the first time, it then proceeds downloading about 250k filters everytime. And until then I can't do any transactions, which is very unfortunate. I hope there is a fix for this, because otherwise I think I have to move to another wallet.

**Comment by yahiheb** [comment]
Usually it takes some minutes to synchronize your wallet and to download the [block filters](https://docs.wasabiwallet.io/glossary/Glossary-PrivacyWasabi.html#block-filters). This can take longer for different reasons.
Just run Wasabi and make sure the backend is connected and your wallet is connected to some peers and let it sync.
