### ISSUE TITLE
Update WalletManagerRecoveryWords.png

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1160]
https://github.com/zkSNACKs/WasabiDoc/pull/1129#issue-1325686623

**Comment by MarnixCroes** [comment]
here https://github.com/zkSNACKs/WasabiDoc/pull/1132
if that is merged, I can add the links to walletgeneration

**Comment by yahiheb** [comment]
> here #1132 if that is merged, I can add the links to walletgeneration

https://github.com/zkSNACKs/WasabiDoc/pull/1132#issuecomment-1207575548

**Comment by MarnixCroes** [comment]
fixed
