### ISSUE TITLE
Update https://en.bitcoin.it/wiki/Wasabi_Wallet

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1166]
As pointed out by @jesseaam

**Comment by yahiheb** [comment]
Also update the section where Wasabi is mentioned in https://en.bitcoin.it/wiki/CoinJoin

**Comment by jesseaam** [comment]
> Also update the section where Wasabi is mentioned in https://en.bitcoin.it/wiki/CoinJoin

I just updated the section that mentions Wasabi: `Sounds great! Where is it?`

**Comment by yahiheb** [comment]
> I just updated the section that mentions Wasabi: [Sounds great! Where is it?](https://en.bitcoin.it/wiki/CoinJoin#Sounds_great.21_Where_is_it.3F)

Good job @jesseaam.

**Comment by jesseaam** [comment]
I finished updating this wiki page, which included the most updates in the [coinjoin section](https://en.bitcoin.it/wiki/Wasabi_Wallet#CoinJoin_via_Wasabi_Wallet). If you all are happy with the text, we can close this issue.

**Comment by yahiheb** [comment]
Good job @jesseaam, can you also check the grammar of that whole wiki page?
IMO it still can be further improved. For example:

> Wasabi Wallet never leaves the Tor onion network and it never uses Tor exit relays, significantly decreasing the network attack surface.

I guess we now use Tor exit relays.

> coin labeling

hmm, it is address labeling.

> Custom change address

We don't have that yet in WW2

> choose a name that you reflects the purpose of the wallet

that reflects ...

> These labels should be the name of the entities you transact with or who may have knowledge about the transaction.

The label should the name of the entities who know that this address is yours.

> it will help you better manage your privacy by enabling the emergence of enhanced UTXO governance.

????

I guess we can update the following picture to show the privacy bar https://en.bitcoin.it/wiki/File:2022.06.15-21--2-.jpg

> CoinJoins are probably the most important feature of Wasabi.

Remove the word `probably`

> a use these funds to sponsors the Wasabi

and use ...

> WabiSabi was introduced

Here we can add a link to the WabiSabi repo. https://github.com/zkSNACKs/WabiSabi

cc @MarnixCroes @BTCparadigm @MaxHillebrand

**Comment by yahiheb** [comment]
`Under normal conditions, Wasabi Wallet never leaves the Tor onion network and it never uses Tor exit relays, significantly decreasing the network attack surface.`

This whole phrase is wrong AFAIU.

**Comment by jesseaam** [comment]
I just updated the main section and incorporated your edits, @yahiheb.

**Comment by jesseaam** [comment]
> I guess we can update the following picture to show the privacy bar https://en.bitcoin.it/wiki/File:2022.06.15-21--2-.jpg

@yahiheb, were you envisioning something like one of the images below? Also, I just noticed that the `Private coin (unconfirmed)` does not appear to be in both images. Has anyone else noticed a discrepancy like this?

<br>

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/18119820/201482034-62ab6d08-512c-4309-8d48-936408508a30.png">


<img width="1456" alt="image" src="https://user-images.githubusercontent.com/18119820/201482071-6ed8de79-5261-4e0a-9b37-e2d792b3d531.png">

**Comment by yahiheb** [comment]
> @yahiheb, were you envisioning something like one of the images below?

The first image. I think this one is better with discreet mode off:

![Capturesss](https://user-images.githubusercontent.com/52379387/201498094-cc871f83-30d6-46ed-aac4-4bd1361d2636.PNG)




> Also, I just noticed that the `Private coin (unconfirmed)` does not appear to be in both images. Has anyone else noticed a discrepancy like this?

Maybe it is a bug. Better to open an issue in the main repo with steps to reproduce.

**Comment by jesseaam** [comment]
OK, used that image instead. 

I created an issue for the coin discrepancy. https://github.com/zkSNACKs/WalletWasabi/issues/9527

**Comment by jesseaam** [comment]
IMO, this issue can be closed. You can verify that all looks well at: https://en.bitcoin.it/wiki/Wasabi_Wallet

**Comment by MarnixCroes** [comment]
closing. 
Current is ok.

@jesseaam thanks for the work.
