### ISSUE TITLE
Simplify 2.0 docs

### ISSUE THREAD

**Issue by BTCparadigm** [zkSNACKs/WasabiDoc#1199]
Proposal: 
Remove "Why Wasabi" and "Building Wasabi" from the docs. Maybe Glossary too.
Focus on "Using" and "FAQ".

Thoughts?

**Comment by MarnixCroes** [comment]
ACK
I'd probably keep the glossary

we could remove it from the main page to simplify, but keep it somewhere else

**Comment by MarnixCroes** [comment]
- Regarding` Building Wasabi `https://github.com/zkSNACKs/WasabiDoc/issues/1571:
> Maybe we could rename the Building Wasabi pillar to Developer, yes it breaks links but might still be worth it.
Then it can contain building wasabi and integrating.

- Regarding `Why Wasabi`
I think it contains useful information, so I'd say to keep it.

close the issue?
