### ISSUE TITLE
white on white text

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#1211]
There is white on white text on the homescreen, and probably other places too?

![2022-09-27-214012](https://user-images.githubusercontent.com/30683012/192620349-dbed4361-351b-48c6-9427-6ba48d51ee18.png)
![2022-09-27-214024](https://user-images.githubusercontent.com/30683012/192620345-5b1d5f76-b870-4057-9b71-4c55240c06c2.png)

**Comment by yahiheb** [comment]
@CAnorbo should be working on this one.

**Comment by yahiheb** [comment]
Fixed by #1247
