### ISSUE TITLE
[DOJO] Integrate SourceCred

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#124]
This was already discussed in #8, but I think a separate issue is good. 

@SourceCred is a powerful tool to get a contribution score to all the many Wasabikas - not just commits with lines added, but many many more customizable attributes. This is very powerful, also as help to spread out the bounty rewards. 

[This thread](https://discourse.sourcecred.io/t/wasabi-wallet-documentation/139/) has a thorough question, and a very very awesome and detailed answer by @decentralion. 

### Next step ToDo's

- [ ] Create new `WasabiCred` repo in the @zkSnacks organization. 
- [ ] Setup SourceCred in this repo
- [ ] Host the result on a GitHub page
- [ ] Link the result in the [Dojo](https://docs.wasabiwallet.io/building-wasabi/Dojo.html)

**Comment by molnard** [comment]
I duplicated this issue for testing reasons but I have got some useful answers there. 
https://github.com/molnard/WasabiDoc/issues/6

**Comment by MarnixCroes** [comment]
What's up with this?
Maybe close it?
