### ISSUE TITLE
Rename Install-package to Download&Install

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1251]
I think many (newbie) users don't know what a package is. (user: _what is a package? I don't want a package, I just want to install the app_)
I´m not even sure if many people know what install exactly is, they just **download** an app and it works😅

renaming it to `Download & Install` is better imo

ACK or NACK?

**Comment by MaxHillebrand** [comment]
ACK

**Comment by yahiheb** [comment]
ACK
