### ISSUE TITLE
Danger message not readable

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#129]
![Danger-message](https://user-images.githubusercontent.com/52379387/62749837-3f1bf600-ba5e-11e9-973f-dc701b4ba61c.JPG)

And why the docs [website](https://docs.wasabiwallet.io/) is not in dark mode?

**Comment by MaxHillebrand** [comment]
Described in #54, @dennisreimann has implemented this magic where it displays the mode that the user selects in his system locally, by default dark mode, so you have explicitly set your computer to white mode. 

But in this config, the danger text must be displayed differently... Are you on this Dennis?

**Comment by yahiheb** [comment]
I didn't change anything in my computer settings.

**Comment by yahiheb** [comment]
@dennisreimann The message is readable now, buy can you highlight the key and email with a different color?
