### ISSUE TITLE
Issues & PRs

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#130]
#126 @nidkil opened an issue that should be asked in the main repository.
I think we should make it clear that issues and PRs open in this repository must be documentation related.

**Comment by MaxHillebrand** [comment]
Very good point, we need to me more proper in the github structure now...

How about we add such [issue and pr templates](https://github.com/zkSNACKs/WalletWasabi/tree/master/.github/ISSUE_TEMPLATE) that explain what is going on?
