### ISSUE TITLE
Define what is anonymity score and how does it compare to anonymity set?

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1330]
The old anonset and the new anonscore has minimal changes to it, so they can be considered the exact same thing.
What differs is the coinjoins they are applied to. In WW1 coinjoins we got unequal inputs, some equal outputs and changes. In WW2 coinjoins many inputs are equal as well, we got equal outputs, and if the output is of unique value it does not mean it's a change. In fact most of the times it's not a change, but a well mixed coin.
The anonymity score is a metric to help the wallet decide when it's time to stop the coinjoining process.

> WW2 doesn't have anonset anymore, it has anonscore; which is different. For example, if the outputs are [1, 1, 1, 1, .5, .5, .5, .5, .4, .4, .2, .2, .2, .2, .2, .1, .1, .1, .1, .1] then, even when each of those 1s have anonscore 4, there is still lots and lots of combinations of outputs that sum up to 1, so the anonset should be much higher but the anonscore is extremely conservative and takes into account many other things so, it uses to give smaller values.

https://tumblebit.slack.com/archives/C35HU7XUJ/p1667495862543319?thread_ts=1667459944.358689&cid=C35HU7XUJ

**Comment by MarnixCroes** [comment]
done
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-is-the-anonymity-score
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-is-the-difference-between-anonymity-set-and-anonymity-score
