### ISSUE TITLE
[Website][FAQ] Reaching an url with anchor doesn't auto expand item when already on the FAQ

### ISSUE THREAD

**Issue by turbolay** [zkSNACKs/WasabiDoc#1339]
It's pretty much an edge case.

https://user-images.githubusercontent.com/16029533/200638200-4861ea09-01bb-40d8-a39b-b368e8f13579.mp4

In first case, I'm already on the doc page so I encounter the issue: when reaching the URL with anchor, item is not correctly auto expanded 
*Note: If you are already on the item anchored url and refresh, it will expand*

In second case, I'm not on the page so it works

**Comment by turbolay** [comment]
Another example, more annoying:


https://user-images.githubusercontent.com/16029533/200656240-b1c986f9-4987-4bbd-9061-ffcd0f93cacf.mp4

**Comment by yahiheb** [comment]
Fixed by #1247
