### ISSUE TITLE
[Website][FAQ] Code ` tag not working in headers

### ISSUE THREAD

**Issue by turbolay** [zkSNACKs/WasabiDoc#1342]
This issue is probably known but I didn't see any mention of it.

It's currently present in:
[How does the `Auto download new version` work?](https://github.com/zkSNACKs/WasabiDoc/blob/aeed292809038c346f8deecd9df8caad0daa34f3/docs/FAQ/FAQ-Installation.md#what-does-auto-download-new-version-in-the-settings-mean)
[What does `Auto download new version` in the settings mean?](https://github.com/zkSNACKs/WasabiDoc/blob/aeed292809038c346f8deecd9df8caad0daa34f3/docs/FAQ/FAQ-Installation.md#how-does-the-auto-download-new-version-work)
[Why is there no `Send` button, only the `Receive` button is displayed?](https://github.com/zkSNACKs/WasabiDoc/blob/abd57c327289f114239bd81506432f82a3880f6f/docs/FAQ/FAQ-UseWasabi.md#why-is-there-no-send-button-only-the-receive-button-is-displayed)
[What does the `Auto-start coinjoin threshold` mean in the coinjoin settings?](https://github.com/zkSNACKs/WasabiDoc/blob/abd57c327289f114239bd81506432f82a3880f6f/docs/FAQ/FAQ-UseWasabi.md#what-does-the-auto-start-coinjoin-threshold-mean-in-the-coinjoin-settings)
[What does the `Red coin isolation` mean in the coinjoin settings?](https://github.com/zkSNACKs/WasabiDoc/blob/abd57c327289f114239bd81506432f82a3880f6f/docs/FAQ/FAQ-UseWasabi.md#what-does-the-auto-start-coinjoin-threshold-mean-in-the-coinjoin-settings)

It looks like this: 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/16029533/200708895-9ffa5828-5a12-4733-af3e-df86f6a2c208.png">

**Comment by yahiheb** [comment]
Fixed by #1247
