### ISSUE TITLE
Add definition for anonymity score

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1367]
Add definition for anonymity score both in the FAQs and the glossary.

https://app.slack.com/client/T34SFJ13J/G01D4AZ0DSQ/thread/G01D4AZ0DSQ-1668532474.026649

> "Anonymity score is a new way to estimate the level entropy of a UTXO in an unequal-but-highly-composable output value coinjoins."
> It is different than anonymity set. For example, if the outputs are [1, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.4, 0.4, 0.2, 0.2, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1] then, even when each of those 1s have anonscore 4, there is still lots and lots of combinations of outputs that sum up to 1, so the anonset should be much higher but the anonscore is extremely conservative and takes into account many other things.

> What is anonymity score and how does it compare to anonymity set?
> 
> The old anonset and the new anonscore has minimal changes to it, so they can be considered the exact same thing.
> What differs is the coinjoins they are applied to. In WW1 coinjoins we got unequal inputs, some equal outputs and changes. In WW2 coinjoins many inputs are equal as well, we got equal outputs, and if the output is of unique value it does not mean it's a change. In fact most of the times it's not a change, but a well mixed coin.

> The anonymity score is a metric to help the wallet decide when it's time to stop the coinjoining process.

**Comment by MarnixCroes** [comment]
> Add definition for anonymity score both in the FAQs and the glossary.

this was fixed
