### ISSUE TITLE
Link preview text

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#137]
### Problem

Right now the link preview text shows always the same, regardless what link is used. This is unspecific and does not give an accurate preview of what the linked content actually is.

![screenshot_20190810_113125](https://user-images.githubusercontent.com/30683012/62820302-9efbc500-bb62-11e9-9dcf-4bf2dd886646.png)

### Solution

Is it possible to give a more precise preview, either for the specific markdown file [in this case a summary of the BIP.md file] or even better, for the specific header within the markdown file [in this case a summary of BIP158].

**Comment by dennisreimann** [comment]
Special preview text for single headers aren‘t possible, as the information is provided on a per page basis. 
The preview text is adjustable via the description meta information, which can be added to the page frontmatter.

**Comment by MaxHillebrand** [comment]
Thanks Dennis!

Just to clarify, at the top of each markdown file we can put this?

```
---
description: foo bar foo.
---
```

**Comment by dennisreimann** [comment]
Yes, for details see the [frontmatter reference](https://v1.vuepress.vuejs.org/guide/frontmatter.html) of VuePress. Providing this information will also help with #40 😀
