### ISSUE TITLE
create Quick start guide

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1383]
we have lots of info and the user has to know where to navigate and in which order: first _install_, then _generate wallet_ etc..
it can be overwhelming

and as a new user, you're likely not going to read the docs first, you just want to give Wasabi a try and see if you like it. Without spending too much time on it.

Quick start guide would be useful
kinda like a blog post

**Comment by BTCparadigm** [comment]
cACK
