### ISSUE TITLE
Add image directory

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#14]
We already have some Wasabi info-graphics, and will most certainly create more. Further, we will have several screenshots of Wasabi in the documentation.

Thus we need to implement the infrastructure to properly store the images in the repo and display the images in GitBook. 

I'm not sure what is best practice, maybe @thunderBiscuit knows?

**Comment by MaxHillebrand** [comment]
For example the Installation Guide uses the following strategy. 
Does this work together with gitbook?

- Upload picture to imgur.
- Write the link in the md like `![](https://imgur.com/wsJ66Qt.png)`
- Result:

![](https://imgur.com/wsJ66Qt.png)

**Comment by thunderBiscuit** [comment]
Yes I noticed that. I'm not sure what is best/easier. Having them somewhere else or keeping them in the repo. For the images that are kept on the repo, I think the best way is to have a directory called something like `img` inside the docs. The links can reference the png images there.

**Comment by MaxHillebrand** [comment]
As I understand it, the image directory for VuePress is [`WasabiDoc/docs/.vuepress/publid`](https://github.com/zkSNACKs/WasabiDoc/tree/master/docs/.vuepress/public)?
So I can start uploading pictures there, and then link in the separate .md files to the image?

**Comment by thunderBiscuit** [comment]
Yes that is right in theory. But to be honest I have had troubles with it in the past... If you test it let us know if it works for any markdown file anywhere in the repo.

**Comment by dennisreimann** [comment]
@thunderBiscuit What have been the problems with that? I think this should be the prefered approach, because it is the simplest way of hosting and integrating the images.

**Comment by MaxHillebrand** [comment]
The proper way to reference images is `![](/image.png)

**Comment by thunderBiscuit** [comment]
Yeah sorry @dennisreimann I don't actually know what I was doing wrong. It's working for me now, and is definitely the recommended way to work it.

ACK.
