### ISSUE TITLE
link not visible in yellow box (cautious warning) on dark mode

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1404]
![image](https://user-images.githubusercontent.com/93143998/208097725-e4835ba5-ff75-4079-b81f-88a0669dff0a.png)

light mode 
![image](https://user-images.githubusercontent.com/93143998/208097797-f8f1a185-9cb9-46c3-81ce-4e329a210390.png)

**Comment by yahiheb** [comment]
How about simply using `tip` instead of `warning` in such cases.

**Comment by MarnixCroes** [comment]
> How about simply using `tip` instead of `warning` in such cases.

These warnings are useful.
imo we should change the color of the hyperlinks

**Comment by yahiheb** [comment]
> imo we should change the color of the hyperlinks

That might take long time to fix that and I don't see any real difference between `tip` and `warning`.

**Comment by MarnixCroes** [comment]
@CAnorbo 
you might know a quick color fix?

**Comment by MarnixCroes** [comment]
fixed
