### ISSUE TITLE
update Reddit pinned post

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1412]
current one contains WW1 related info
https://www.reddit.com/r/WasabiWallet/comments/c7w7ua/user_guide_faq_and_10_commandments/

**Comment by MarnixCroes** [comment]
@kruwed would you like to fix this?

**Comment by Kruwed** [comment]
Yes, I can update this.

**Comment by Kruwed** [comment]
I've pinned a concise guide with warnings, tips, and links: https://www.reddit.com/r/WasabiWallet/comments/19bg3pd/wasabi_wallet_help_information_start_here/

**Comment by yahiheb** [comment]
Just small nit:

Can you also add the link to the PGP fingerprint:
> - Verify your download with zkSNACKs’ PGP: [6FB3 872B 5D42 292F 5992 0797 8563 4832 8949 861E](https://github.com/zkSNACKs/WalletWasabi/blob/master/PGP.txt)

Mention that currently there is no mobile version (Alert).

Wasabi is an open source Bitcoin wallet for Linux, Mac **for desktop**.

> There is a cost tradeoff for using the optional coinjoin feature. 

I would remove the word "optional" since auto-coinjoin is on by default.

**Comment by Kruwed** [comment]
@yahiheb I have updated it with the changes.

**Comment by MarnixCroes** [comment]
thank you @Kruwed well done!
