### ISSUE TITLE
dark theme sidebar background on mobile 

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1420]
![image](https://user-images.githubusercontent.com/93143998/210756142-dbe8c433-ac47-4c6b-aaf3-c53c607a95f8.png)

### should be like white theme
![image](https://user-images.githubusercontent.com/93143998/210756093-3ffb00fa-a29b-4516-b3c4-720aca081db9.png)

**Comment by BTCparadigm** [comment]
Oof, that's ugly.

**Comment by yahiheb** [comment]
Fixed by #1423
