### ISSUE TITLE
add CPFP fee bump for incoming tx

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1447]
Have a step by step for CPFP of outgoing https://github.com/zkSNACKs/WasabiDoc/pull/1443 and incoming tx's.
So also add one for incoming

(Until the UI/UX changes to a simple click _bump fee_)

Change the tile of current FAQ?
How can I bump the transaction fee with child pays for parent (CPFP)? -> How can I bump the transaction fee **for an outgoing transaction** with child pays for parent (CPFP)?

so we can slo have one: How can I bump the transaction fee **for an incoming transaction** with child pays for parent (CPFP)?

ACK? other ideas?

**Comment by yahiheb** [comment]
> Have a step by step for CPFP of outgoing #1443 and incoming tx's.
> So also add one for incoming

IMO we should just have one general CPFP question for both incoming and outgoing txs.

**Comment by MarnixCroes** [comment]
> IMO we should just have one general CPFP question for both incoming and outgoing txs.

Yes I thought about it.
Right now it's at the send section, if we want to include receive in the same FAQ it should be replaced.
Move it to General? should we create a new section `Advanced`?

**Comment by yahiheb** [comment]
We should simply make #1443 cover both cases and keep it in the Send section, because CPFP is technique to send btc.

**Comment by MarnixCroes** [comment]
this was added
