### ISSUE TITLE
What do you need to get the keys?

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#145]
I would love an explanation of [this](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/using-wasabi/WalletGeneration.md#what-do-you-need-to-get-the-keys). I do not really get it.
The title says `What do you need to get the keys?` but reading that do not answer that question.

**Comment by MaxHillebrand** [comment]
Yes, this is only somewhat of a placeholder based on [this](https://github.com/zkSNACKs/WalletWasabi/issues/2049#issuecomment-520192355) very good knowledge by @lontivero - I just didn't have time to write it out properly...

Lucas, if you have some spare time, maybe you can write up some more of the details? [not your priority though!]

**Comment by lontivero** [comment]
> What do you need to get the keys?

In that section I list all the possible pieces of data that can be used to recover a HD wallet. In other words: all the ways with can compute the (master) extended key.

The details about how to get the privates keys from an extended key is specified in the bip32 and I am sure I cannot explain it better. https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by yahiheb** [comment]
@MaxHillebrand From your list:
**Data**: entropy | **Does it need password to recover?** No, this is unencrypted
You don't need the password to decrypt it (because it is unencrypted) **but** you need the password to recover the wallet.
@lontivero Your list and Max's list are different.

**Comment by MaxHillebrand** [comment]
closed by #396

**Comment by yahiheb** [comment]
This is not solved yet.
