### ISSUE TITLE
Update Restoring Wasabi Wallet in Electrum

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1452]
The `Extended Account Private Key zprv` was removed in https://github.com/zkSNACKs/WalletWasabi/pull/9742, because according to Lucas:
> The problem with zprv is that it is for m/84'/xxxxx + segwit only and now we have taproot too.

An example of a user trying to recover with Electrum, but he couldn't because `Extended Account Private Key zprv` is missing from the WW v2.0.2.1 and docs are not up to date. https://github.com/zkSNACKs/WalletWasabi/discussions/10183

We should update the docs accordingly.

Also Lucas mentioned that `there is a tool on electrum that can discover your keys. Honestly I don't remember much but that's would be the way. `
Is this worth investigating how this tool works and mention it in the docs?

**Comment by MarnixCroes** [comment]
> Also Lucas mentioned that there is a tool on electrum that can discover your keys. Honestly I don't remember much but that's would be the way. 
Is this worth investigating how this tool works and mention it in the docs?

there is such a thing, but we should not mention it.
