### ISSUE TITLE
Update Standard denominations

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#1491]
These are still old only up to 1.3k btc, they go up to 40k btc now
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-is-the-anonymity-score

**Comment by yahiheb** [comment]
Maybe this should be updated first: https://github.com/zkSNACKs/WalletWasabi/blob/0c6455e05ccbc3701be0763578ff327fc296bdaa/WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs#L12-L22

**Comment by MaxHillebrand** [comment]
Thanks for clarifying, I didn't know this.
