### ISSUE TITLE
Replace youtube thumbnails by custom images

### ISSUE THREAD

**Issue by turbolay** [zkSNACKs/WasabiDoc#1497]
Sorry @MaxHillebrand, I think that you are really pretty, but this is not serious:

![](https://img.youtube.com/vi/mTrClVA_o5A/maxresdefault.jpg)

My proposed solution is to make a really simple design featuring Wasabi and Youtube logo and to replace every 
`![Watch the video](https://img.youtube.com/vi/mTrClVA_o5A/maxresdefault.jpg)`
by the custom image.

**Comment by MaxHillebrand** [comment]
You know, I was always too lazy to make custom thumbnails, good that after all those years someone is cleaning up the slack!

To be honest, we can probably replace all these ancient videos with new custom ones and do a much better job.
