### ISSUE TITLE
Document the 'Cancel + Speed Up (RBF/CPFP) Transaction' features

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1559]
Once https://github.com/zkSNACKs/WalletWasabi/pull/10976 is merged

**Comment by yahiheb** [comment]
We now have an FAQ on how to speed up a transaction, should we add a separate FAQ for how to cancel a transaction?

**Comment by MarnixCroes** [comment]
> We now have an FAQ on how to speed up a transaction, should we add a separate FAQ for how to cancel a transaction?

yes https://github.com/zkSNACKs/WasabiDoc/pull/1583
