### ISSUE TITLE
Add wcli

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#1562]
Wasabi command line interface (wcli) is a wrapper around the RPC, it's very useful, and should be documented.

https://github.com/zkSNACKs/WalletWasabi/tree/master/Contrib/CLI

**Comment by yahiheb** [comment]
Closing this for the following reasons: https://github.com/zkSNACKs/WasabiDoc/pull/1657#issuecomment-1912163246

**Comment by MarnixCroes** [comment]
this can be closed as well then? https://github.com/zkSNACKs/WasabiDoc/pull/1657#issuecomment-1912163246

at least if anyone wants some docs they can check the closed pr😂
