### ISSUE TITLE
Search in content

### ISSUE THREAD

**Issue by turbolay** [zkSNACKs/WasabiDoc#1612]
Currently, the search bar only searches in the titles, it would be much better to search in the content as well.
I talked to @CAnorbo about it a few months ago and if I remember correctly there should be an option just to change this behavior.

**Comment by CAnorbo** [comment]
For this, there is a 3rd party search engine called Algolia that we could use with VuePress.
First, we have to send our website for indexing and they'll give us an API key.

Read more here: https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html

**Comment by turbolay** [comment]
Can we proceed with this? I think it would be a really nice improvement. I've seen it's free and it seems easy to implement

**Comment by MaxHillebrand** [comment]
We're already using algolia, afaik it searches content too.

**Comment by turbolay** [comment]
> We're already using algolia, afaik it searches content too.

We are only searching in the titles right now. 
In our doc, ctrl c + d a line from the doc and you won't have result
In this doc https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#indexname, ctrl c + d a line will find the relevant article. It's much better. I'm having a really hard time navigating the doc because of this.

**Comment by yahiheb** [comment]
Fixed by #1613.

**Comment by yahiheb** [comment]
Reopening this since #1613 was reverted temporarily by #1617

**Comment by yahiheb** [comment]
Again reopening this since #1622 was reverted by #1625

**Comment by molnard** [comment]
👁️

**Comment by MarnixCroes** [comment]
cACK

@CAnorbo any plan for this? -> steps what to do next?

**Comment by CAnorbo** [comment]
We have two options, the old search or the new. Choose one and go with it.
It's a really basic framework, if we'd like to keep it, there are no other options.

**Comment by MarnixCroes** [comment]
ok. 
the new search would be great, if it works correctly.
It was removed because some basic searches were missing/not working.

**Comment by CAnorbo** [comment]
It's a scheduled crawler., that runs I guess daily.

**Comment by molnard** [comment]
@yahiheb What is the status of this?

**Comment by yahiheb** [comment]
There is nothing new about it, @CAnorbo tried to fix this using Algolia but couldn't get it to work properly so we reverted the changes.

**Comment by molnard** [comment]
Maybe there was a misunderstanding. What is the next step @yahiheb ? wontfix?

**Comment by yahiheb** [comment]
No it is not `wontfix`, I think we should simply leave this issue open, and maybe get back to it once we figure out how to properly configure Algolia, or once we have a another solution.

**Comment by molnard** [comment]
> once we have a another solution

Is there another solution?

**Comment by yahiheb** [comment]
> Is there another solution?

I don't know.

**Comment by molnard** [comment]
> I don't know.

Can you look around or make someone look around?

**Comment by yahiheb** [comment]
I guess using Algolia is good, we just need to figure out how to properly configure it.

These projects use Algoli and it works well:
https://docs.btcpayserver.org/
https://v2.vuepress.vuejs.org/

**Comment by molnard** [comment]
So it was reverted last time - before configuration?

**Comment by molnard** [comment]
How to proceed to avoid similar situation @yahiheb ?

**Comment by molnard** [comment]
What is the next step here @yahiheb ?

**Comment by yahiheb** [comment]
As I have mentioned above and as I have told you last week on Slack we could check how some of the projects use Algolia to search in content.

**Comment by molnard** [comment]
And what did you find?

**Comment by yahiheb** [comment]
Btcpaysernver uses Algolia in there docs, maybe these issues/PRs can help us fix this:
https://github.com/btcpayserver/btcpayserver-doc/issues/628
https://github.com/btcpayserver/btcpayserver-doc/pull/530
https://github.com/btcpayserver/btcpayserver-doc/pull/630
https://github.com/btcpayserver/btcpayserver-doc/pull/794

**Comment by CAnorbo** [comment]
Made a new PR, pls test: https://github.com/zkSNACKs/WasabiDoc/pull/1672

**Comment by molnard** [comment]
I give up. I have no more energy for this, good luck to whoever will be my successor. 

![CryingSadGIF](https://github.com/zkSNACKs/WasabiDoc/assets/9844978/b65960d0-de08-4516-a312-b2ba0e9019a4)

**Comment by turbolay** [comment]
This issue was a really great display of absolute lack of skills, project management, care of the contributors for the project.

 A lead that says "I tried all I could" when in fact he simply spammed "what's up with this?" without doing anything.
A maintainer of the docs that passed down the problem to someone else when he simply tried to make the first step
A maintainer of the server that failed in 2 months to simply deploy a test version of the docs.........

**Comment by molnard** [comment]
The one who will achieve success here can only judge me!
