### ISSUE TITLE
searchbar is broken

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiDoc#1614]
cannot find links
some links give 404
some links have header from 1.0 docs like File Manager
if you click on a link it goes to a totally different one

cannot find simple things like rescan or resync

**Comment by yahiheb** [comment]
@CAnorbo I have experienced the same, it doesn't work like before, can you take a look at it.

Also the search bar is still unnecessarily big IMO.

![image](https://github.com/zkSNACKs/WasabiDoc/assets/52379387/543a0612-7cf9-40d4-9483-157a9209379f)

**Comment by CAnorbo** [comment]
I’m using the old index but I don’t have access to that. I thought it updated itself somehow. When I tested, I couldn’t find any issue. Tomorrow I’ll try to find a way either to update this index or create a new one.
