### ISSUE TITLE
Banned error

### ISSUE THREAD

**Issue by Mariachile** [zkSNACKs/WasabiDoc#166]
> Please know that you are opening an issue in the [Wasabi documentation](https://github.com/zkSNACKs/WasabiDoc) repository.
If you have an issue regarding the software specifically, please [open an issue in the main Wasabi repository](https://github.com/zkSNACKs/WalletWasabi/issues/new/choose).

### What is the general context of your question?

Please explain which general pillar your question is about.
There are many different topics covered in the Wasabi documentation, so it's good to start with a general description of your question.
- About general Bitcoin privacy and [why Wasabi](https://docs.wasabiwallet.io/why-wasabi/) is important.
- About the nuances of how to properly [use Wasabi](https://docs.wasabiwallet.io/using-wasabi/) and privacy best practices.
- About how to [contribute to Wasabi](https://docs.wasabiwallet.io/building-wasabi/) and to help the project grow.

### What is your question?
Everything has been running well for me for several days. Today, I made another deposit and things began running but after about an hour I got the message saying: "The coordinator banned this coin from participation until 2019-08-24 :17:20."  All coins are flagged banned except the zerolink change. That time passes and I still remain banned. Nothing about this in the docs. Please advise

**Comment by kravens** [comment]
Did you close the Wasabi Wallet after registering those coins?
When doing a CoinJoin it is necessary for the WasabiWallet to be open, read about coins being banned here: 
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#coinjoin

**Comment by Mariachile** [comment]
Hi Kevin,
Thanks for getting back to me so quickly.
No, I did not close the wallet any time recently. It finished a batch, I sent it out and deposited another amount of BTC. It began working on that and then later showed the banned message. It held the banned position for several hours and then began processing again. By the next morning everything was processed.
Unable to find any info about Banned at that link.

All the best,
MC

**Comment by yahiheb** [comment]
Take a look at this [thread](https://www.reddit.com/r/WasabiWallet/comments/c3fzi0/coin_banned_from_cj_why/).

**Comment by Mariachile** [comment]
thanks, yahiheb

**Comment by MaxHillebrand** [comment]
Hope you got this sorted out by now, it should be only a couple hour time-out.
This is not an issue for the documentation, so I'm closing :)
