### ISSUE TITLE
Import existing articles?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#17]
Several peers have written great articles and posts about Wasabi.

Should we import the text of them directly into the documentation so that the knowledge archive is more and more thorough?

Or should we only summarize them and link to the original?

For example, Nopara has this great article about [Bitcoin Core vs Wasabi Wallet — Network Level Privacy](https://medium.com/@nopara73/bitcoin-core-vs-wasabi-wallet-network-level-privacy-bdca1d501387). Should we copy the text into a `NetworkPrivacy.md` and link it in [`Load Wallet`](https://github.com/zkSNACKs/WasabiDoc/tree/master/docs#load-wallet)? Or should we break up and summarize the content into separate topics?

**Comment by MaxHillebrand** [comment]
Another one are the [10 commandments](https://www.reddit.com/r/WasabiWallet/comments/c7w7ua/user_guide_faq_and_10_commandments/)

**Comment by MaxHillebrand** [comment]
well, I did it in #19 and #20. 
Not sure if we should leave them like this, or maybe change and adapt them, but regardless, good starting point!

**Comment by nopara73** [comment]
You'll find yourself in a big mess if you start duplicating texts. The source will get updated and changed. 😄

**Comment by MaxHillebrand** [comment]
Agreed, I think it's better to, if at all, start with the original text, but then adjust it to be fitting for the docs.
