### ISSUE TITLE
Need to improve mobile UX

### ISSUE THREAD

**Issue by RiccardoMasutti** [zkSNACKs/WasabiDoc#180]
We should add the menu (which is on the left sidebar on Desktop verison) under every chapter on Mobile version:
- Why Wasabi
- Using Wasabi
- Building Wasabi
- FAQ

![WasabiDocMobileUX1](https://user-images.githubusercontent.com/46527252/64529776-ec0eba80-d30b-11e9-8220-a55429fde2c7.png)

Essentially, when the end user enters any 'main' page, it displays nothing except a small description and is forced to open the menu to see the actual content:

![WasabiDocMobileUX2](https://user-images.githubusercontent.com/46527252/64529982-5f183100-d30c-11e9-9211-49ca1028cb97.png)

Desktop version:
![WasabiDocDesktopUX1](https://user-images.githubusercontent.com/46527252/64530414-5bd17500-d30d-11e9-98c6-424b4136c873.png)

**Comment by MaxHillebrand** [comment]
As far as I know, there is no automatic table of content for several .md files... `[[toc]]` works only for headers within one .md file. 

We should write a better introduction for these READMEs about the generals of that pillar.

**Comment by RiccardoMasutti** [comment]
Fixed with #183. Need to write a better introduction in the future

**Comment by yahiheb** [comment]
You shouldn't close this issue, #183 is not merged yet.
