### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/WasabiDoc#187]
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/Guides/InstallInstructions.md

https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md

@MaxHillebrand This is important! These links shall not be broken!

**Comment by nopara73** [comment]
fixed

**Comment by MaxHillebrand** [comment]
Where did you find the broken link, and where is it fixed?

**Comment by nopara73** [comment]
All links were broken, not only these, by removing the security.md that was copypasted from the code repo.
