### ISSUE TITLE
Incorrect statement about local node in FAQ page

### ISSUE THREAD

**Issue by lontivero** [zkSNACKs/WasabiDoc#199]
### General Description

In the FAQ page [here](https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#how-is-the-tansaction-broadcasted) there is an statement that says: _"If a user has a local Bitcoin node running, Wasabi will attempt to broadcast transactions from there."_

That is incorrect. Currently, local node is used only for getting blocks.

### Screenshots

![image](https://user-images.githubusercontent.com/127973/64931561-98223b00-d80f-11e9-96a6-60dadae0e0b4.png)

**Comment by yahiheb** [comment]
Do you have a suggestion to correct that?
