### ISSUE TITLE
Coin Join ? CoinJoin ? coin join ? Coinjoin ? Coin-Join ?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#27]
We should be coherent with the spelling and formatting throughout the documentation.

So, which is it?

1. Coin Join
2. CoinJoin
3. coin join
4. Coinjoin
5. Coin-Join

[any other options?]

**Comment by nopara73** [comment]
@gmaxwell consistently used CoinJoin when he coined the term: https://bitcointalk.org/index.php?topic=279249.0

**Comment by MaxHillebrand** [comment]
Ok, then let's go with GMax' original vision!
I'll make a PR to change all the wording.
