### ISSUE TITLE
Documentation for Transaction Builder?

### ISSUE THREAD

**Issue by jonathancross** [zkSNACKs/WasabiDoc#278]
I didn't see any documentation for the _**Build Transaction**_ tab in Wasabi or on https://docs.wasabiwallet.io

Specifically, it looks identical to the **_Send_** tab (other than the button label) -- maybe there is some way to highlight the reason it exists, what it offers?

Is it just for creating PSBT?

Thanks.

**Comment by nopara73** [comment]
Actually I can just transfer the issue.

**Comment by nopara73** [comment]
Regarding the two tabs, the only difference is that the Build Transaction does not propagate the transaction, it simply builds it. It works differently for watch-only and hardware wallets than normal wallets.

In summary:

|              | hot wallet            | watch-only wallet     | hardware wallet       |
|--------------|-----------------------|-----------------------|-----------------------|
| build tx     | send tab, buildtx tab | send tab, buildtx tab | send tab, buildtx tab |
| sign tx      | send tab, buildtx tab |                       | send tab              |
| broadcast tx | send tab              |                       | send tab              |

**Comment by MaxHillebrand** [comment]
The above summary is merged in the docs now, and also note that there is a full [cold-wasabi protocol](https://docs.wasabiwallet.io/using-wasabi/ColdWasabi.html) that goes into the details of the tx building tab as well.

Closing the issue for now, if there is more to cover in the docs then please [open an issue / pr](https://github.com/zkSNACKs/WasabiDoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) there :)

**Comment by jonathancross** [comment]
Perfect, thanks!
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-s-the-difference-between-send-and-build-transaction
