### ISSUE TITLE
ColdWasabi documentation is incomplete

### ISSUE THREAD

**Issue by fresheneesz** [zkSNACKs/WasabiDoc#290]
The following page seems like its not complete: https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/using-wasabi/ColdWasabi.md

There is random text that says ":::details" - are those supposed to be links? There is a title for a workflow diagram at the bottom that has no content. It seems like there's no information on the PSBT protocol.

**Comment by yahiheb** [comment]
It is complete. Take a look here:
https://docs.wasabiwallet.io/using-wasabi/ColdWasabi.html

**Comment by fresheneesz** [comment]
@yahiheb Why are the images not visible in the source on github? Its confusing to have the '.md' extension when it seems this is not just a normal markdown file.

**Comment by yahiheb** [comment]
@dennisreimann

**Comment by dennisreimann** [comment]
The Markdown files serve as a basis for the content shown on the [website](https://docs.wasabiwallet.io/). Even though the comntent can also mostly be consumed here on GitHub, the website should be considered the primary way to look at the content. Think of these files like database entries for a content management system – they contain the raw material, which is enhanced by [VuePress](https://github.com/zkSNACKs/WasabiDoc#vuepress), which builds the final website.
