### ISSUE TITLE
[FEATURE] Algolia for Activate Content Search

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#38]
Out-of-the-box, VuePress provides a search box that is looking through only the headers of all the markdown files. As far as I understand, there is an opt-in extension to allow the search for the text in the files.

I think we should activate this, but it might lead to a cluttered search experience.

**Comment by MaxHillebrand** [comment]
Related to #40

**Comment by MaxHillebrand** [comment]
VuePress doc suggests [Algolia DocSearch](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#algolia-docsearch) for full text search, but this requires some extra indexing.

**Comment by dennisreimann** [comment]
[Algolia](https://community.algolia.com/docsearch/) seems to be a good option and is free for open source projects. According to [their docs](https://community.algolia.com/docsearch/who-can-apply.html) we can apply, which I think would be worth trying once the docs URL is decided on. (The URL needs to be provided when applying)

**Comment by MaxHillebrand** [comment]
Oh, sorry for slacking on this application, I completely forgot that this is my ToDo...
I applied now - let's see when and how they get back!

**Comment by dennisreimann** [comment]
Have they gotten back to you yet? Asking because they have sent me the API key two weeks after applying …

**Comment by dennisreimann** [comment]
@MaxHillebrand any news on that?
