### ISSUE TITLE
Removing free advertisement for bad companies

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#406]
We have now several cases where we give a shoutout specifically to companies that do not deserve free advertisements. This is especially `Coinbase`, an incredibly bad actor in the space. I am **extremely** against mentioning them at all in this documentation, other than for highlighting their horrendously bad privacy and custodianship. For example the list of [transaction surveillance companies](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/why-wasabi/TransactionSurveillanceCompanies.md#examples) is a good place to call out these bad actors, because it is done so by highlighting their unethical bad behavior. On the other hand there can be mentions of good actors, like `Bull Bitcoin` if it is in the context of highlighting how they are protecting the privacy of their users.

So I open the issue to get your thoughts on if we should replace for example `Coinbase` with `KYC exchange` in any place of the docs where such a generic term is applicable.

**Comment by RiccardoMasutti** [comment]
NACK. I believe instead that we should leave them because they are the best known. Most of our users probably bought the first bitcoins there.

**Comment by yahiheb** [comment]
I am in favor of removing them as well, but I understand that maybe most users know about them, and it is easier for people reading the docs to understand the examples when we mention `Coinbase` for example.
How about whenever we mention them we add between brackets that they are bad actors in the space.

**Comment by MaxHillebrand** [comment]
Well, people only know about Conbase because we continue talking about them... I hope many new comers will never interact with them, thus they will be confused. Especially because Coinbase is an actual term for the miner payout, so this might actually confuse them even more.

Kraken, or Bitfinex, or Binance [hehe, why not advertise them, they like CoinJoin :wink:] are also a world known exchanges, so why favor one over the other? 

Yes, there are some cases where naming one exchange particularly is needed, but I think that is only a couple times. I would like to remove any specifics for as much as possible, and keep it with a generic name. Also emphasizing that `*KYC* exchange` makes sure that these are coins linked to your meatspace identity, and thus need to be handled with extra care. By having just the brand name, this is not directly clear.

**Comment by jesseaam** [comment]
I believe [PR 528](https://github.com/zkSNACKs/WasabiDoc/pull/528) resolves this issue, correct?

**Comment by yahiheb** [comment]
> I believe [PR 528](https://github.com/zkSNACKs/WasabiDoc/pull/528) resolves this issue, correct?

I guess so.
