### ISSUE TITLE
VuePress Table of Content

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#41]
As described in the [VuePress Documentation](https://vuepress.vuejs.org/guide/markdown.html#table-of-contents), there is an automated tool to generate a table of contents. When we input `[[toc]]` anywhere in the markdown, it will automatically populate a hyper-linked bullet-point table of contents of the headers [default level 2 & 3] in this file. It can be configured in [`markdown.toc`](https://vuepress.vuejs.org/config/#markdown-toc)

### Pro

- Easy to input, literally just `[[toc]]`.
- Automatic update, seems like this is set it and forget it.
- Easy consistency across all the files. 

### Con

- Takes the header name, and cannot give extra context, like I've so far done in the hand-made ToC.
- Sub-headers might not want to be integrated in a specific file, not sure how in depth this can be customized.

## Question

Should we continue to do a manual table of content in the files that need it, or should we work with this automated feature?

**Comment by dennisreimann** [comment]
> Sub-headers might not want to be integrated in a specific file, not sure how in depth this can be customized.

There is the [`includeLevel` option](https://www.npmjs.com/package/markdown-it-table-of-contents#options) for the [advanced markdown config](https://vuepress.vuejs.org/guide/markdown.html#advanced-configuration), which can be used to set the levels generally. 
AFAIK there is no way to configure the levels individually for each TOC.

However, I'd just keep it as it is and use the default, which works pretty good IMHO.

+1 from my side, TOCs are nothing one would like to take care of manually.
