### ISSUE TITLE
Supported BIPs: BIP-0142 (withdrawn base58 "p2..." segwit addresses)

### ISSUE THREAD

**Issue by SomberNight** [zkSNACKs/WasabiDoc#413]
Is BIP-0142 really supported?
https://github.com/zkSNACKs/WasabiDoc/blob/a4d3f2e47cb696aa9bc0846cf9693ea3bb676384/docs/using-wasabi/BIPs.md#bip-142-address-format-for-segregated-witness

**Comment by MaxHillebrand** [comment]
> This BIP describes new types of Bitcoin address to support native segregated witness transactions with 20-byte and 32-byte program. 

As I understand it, these are the native segwit bech32 addresses `bc1q...`. In this case, yes, they are supported by Wasabi. Though I might be mistaken that this is a different address format?

**Comment by MaxHillebrand** [comment]
Damn, you are right @SomberNight!! 
BIP 142 is NOT the address format that wasabi is using, but rather BIP 173, which is already linked in the docs.
