### ISSUE TITLE
Make search results scrollable 

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#449]
Apparently there is a way to have a [scrollable search result list](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/infinite-scroll/js/). 
It would be nice to have a way to see ALL the search results, not just the top 25 [#448].

Maybe it would be a nice solution to have a right side search menu, scrollable or with pages, similar to the [Agolia docs](https://www.algolia.com/doc/).

![screenshot_20191224_133010](https://user-images.githubusercontent.com/30683012/71413293-c8207c00-2651-11ea-89b8-6ac4a9bdb2f8.png)

**Comment by yahiheb** [comment]
That can be good, but also imagine you get 100 results that is too much.
