### ISSUE TITLE
Open FAQ dropdown when searched

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#451]
In the old search engine, if I clicked on a FAQ search result, then it jumped to that header in the file and also opened the dropdown.

With the Algolia search engine, it does only jump to the ### header, but it does not open the dropdown, which makes it a bit cumbersome to search the FAQ, as the result is not immediately clear.

Can Algolia also open the dropdown?

**Comment by dennisreimann** [comment]
> Can Algolia also open the dropdown?

Yes it can 😁
