### ISSUE TITLE
Open search results when clicked

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#476]
### Problem

How to reproduce:

- Search a term in the search bar
- Click on the result, it will send you to that section, and the result box closes, but the searched term stays in the search bar
- Now click on the search bar again, and even press enter, the result box is not shown
- Only way to get the results, is to delete the last letter, and type it again

### Solution

If there is a term in the search bar, as soon as it is clicked, open the search result box.

@dennisreimann, do you know some algolia wizzardry for this?

**Comment by dennisreimann** [comment]
Added it to my general Algolia PR.

**Comment by yahiheb** [comment]
I can confirm it is fixed in the Algolia PR (we should mention that the other PR fixes this).

One thing I noticed though:

> - Search a term in the search bar
> - Click on the result, it will send you to that section, and the result box closes, but the searched term stays in the search bar

AND the search bar still has the focus.
IMO it would be better for the search bar to lose the focus so once it is clicked again the result box appears.

**Comment by RiccardoMasutti** [comment]
@dennisreimann are you manually updating algolia updates to wasabi docs?
