### ISSUE TITLE
Add plugin "progress bar"

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#48]
There is an official [plugin](https://v1.vuepress.vuejs.org/plugin/official/plugin-nprogress.html) to provide a progress bar of how far the document is read. This might be a nice touch and make everything look a bit more pertty.
I think this is useful for Wasabi Doc because the files can get rather long, and a reference of how much is still left is good.

I suggest we implement this, what do you think?

#46 #47 are also plugin, so implementation might be batched.

**Comment by dennisreimann** [comment]
This is not for the reading state, but a [loading indicator](http://ricostacruz.com/nprogress/). It is already included in the build by default :)

**Comment by MaxHillebrand** [comment]
Ah, I see - thanks for clearing this up!

Do you know of an easy way to add such a reading state though?
And do you think this is useful in general?

**Comment by dennisreimann** [comment]
To be honest, I find those rather distracting and IMHO the scrollbar should give a good impression on how far one has progressed in case one is interested in keeping track.
