### ISSUE TITLE
Wasabi tutorials in Portuguese

### ISSUE THREAD

**Issue by lontivero** [zkSNACKs/WasabiDoc#498]
This guys https://bitcoinheiros.com have a couple of videos about Wasabi in Portuguese, it would be good to include them:

* https://youtu.be/0tSIOUAKDyY
* https://youtu.be/LTvTK0J1hRI
* https://youtu.be/De1m-XXuMtA

**Comment by yahiheb** [comment]
The first link is about Coldcard only, I think you wanted to share this link instead:
https://youtu.be/JKfPjKXcsAw

**Comment by lontivero** [comment]
No. The video title says "Use your Coldcard with Wasabi" and they run wasabi and explain that all goes trough Tor mong other things about wasabi. The video is not 100% about Wasabi but it is 50% about it.

**Comment by yahiheb** [comment]
> - https://youtu.be/0tSIOUAKDyY
> - https://youtu.be/LTvTK0J1hRI
> - https://youtu.be/De1m-XXuMtA

I meant the first link which its title says `Understand Coldcard's "Danger Zone"`.

**Comment by lontivero** [comment]
Oh you're right.

**Comment by MarnixCroes** [comment]
These are about WW1.
AFAICT they don't have any video's about WW2.
Close this issue?
