### ISSUE TITLE
Slow tag jump

### ISSUE THREAD

**Issue by molnard** [zkSNACKs/WasabiDoc#516]
1. Go to https://docs.wasabiwallet.io/using-wasabi/InstallPackage.html
2. Click on macOS
3. It starts to scroll down.

Suggestion: the scrolling takes to long. I would remove the animation and just jump there.

**Comment by MaxHillebrand** [comment]
This was introduced by @RiccardoMasutti in #457. 

@molnard, for me the scroll happens very quickly, it's done within less than one second, so I don't think it is too slow, but rather a nice animation to give more spacial awareness.

**Comment by yahiheb** [comment]
> Suggestion: the scrolling takes to long. I would remove the animation and just jump there.

ACK

> @molnard, for me the scroll happens very quickly, it's done within less than one second, so I don't think it is too slow, but rather a nice animation to give more spacial awareness.

I agree that it looks nice but if it is slow for some readers then IMO it is better to remove it.

**Comment by molnard** [comment]
For me it is 2.37 sec if I click on macOS.

**Comment by yahiheb** [comment]
> For me it is 2.37 sec if I click on macOS.

Me too it is something over 2 seconds.

**Comment by MaxHillebrand** [comment]
> For me it is 2.37 sec if I click on macOS.

Mhhh, that's odd... for me it is 0.54 seconds, in both the local build as well as deployed website.
2.37 is clearly too long, though I'm very curious why it is so quick for me...

**Comment by molnard** [comment]
This is still an annoying thing. I am sure that this works similarly on win10 google chrome users as @yahiheb confirmed. 

I would remove the animation at all - this is not a designer website and it does not add extra experience to the user.
