### ISSUE TITLE
Wasabi generating watching wallet with wrong master fingerprint

### ISSUE THREAD

**Issue by 3ndpoint** [zkSNACKs/WasabiDoc#532]
After creating a wallet on Coldcard and securing it with a passphrase I exported it to a Wasabi skeleton file (new-wasabi.json). Opening the skeleton file I find that the master fingerprint matches the master fingerprint of the Coldcard. Upon importing the skeleton file and loading the resulting watching wallet in Wasabi, I find that the master fingerprint of the resulting wallet is different from both the Coldcard/new-wasabi.json master fingerprints.
I re-imported and reloaded a second wallet from the same json file into Wasabi to see if this was a glitch: same wrong master fingerprint. I also tried not entering the passphrase on the Coldcard to see if the master fingerprint would match the Wasabi watching wallet: no good, different fingerprint from either previous.
I'm new to both Wasabi and Coldcard. Before I realized the distinction between wallet fingerprints I did send a small amount of bitcoin to Wasabi wallet with the wrong fingerprint for testing. As might be expected I am not able to access that bitcoin by psbt.
The important part is that a skeleton file with one fingerprint is generating a watching wallet with another fingerprint. Am I doing something wrong? Is there a better place to ask this question. Have I lost the test bitcoin?

**Comment by 3ndpoint** [comment]
Duplicate of my last.

**Comment by pkdvalis** [comment]
Hi, just curious if you were able to sort this out?
