### ISSUE TITLE
To darkmode, or not to darkmode?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#54]
The question is simple:
> Do you like your eyes bleeding?

If the answer is no, then the only logical solution is to make the docs in dark mode.

### Why Dark Mode?

- A paper is white by default, thus we use black inc to write. A screen is black by default, thus we use white pixels to write.
- The high contrast of dark background and white text is a lot easier to read.
- Wasabi GUI is already dark mode.
- Bitcoin is already boiling the oceans, so we should save energy, and dark pixels need less electricity than white ones.

### Why White Mode?

- It might be an adventure to be blind due to white screen radiation.
- Education is not important, so nobody needs to read the docs anyway.
- Babies are dying.

### Comparison

![screenshot_20190803_091827](https://user-images.githubusercontent.com/30683012/62408906-e36dea80-b5cf-11e9-8d5a-7ac8f7f7e141.png)

Looks nice, right? [The button should have a different color]

![screenshot_20190803_091846](https://user-images.githubusercontent.com/30683012/62408912-f1bc0680-b5cf-11e9-929f-f091f367727a.png)

Sorry for making your eyes cry...

![screenshot_20190803_091920](https://user-images.githubusercontent.com/30683012/62408916-fb456e80-b5cf-11e9-9cee-34a6ed0b4856.png)

Easy to read, right? [The highlighted links will be the same color, this is a bug in my dark mode plugin]

![screenshot_20190803_091908](https://user-images.githubusercontent.com/30683012/62408921-0d271180-b5d0-11e9-8516-9b6052a85e9f.png)

Yeah, you don't want to continue reading, right?

### Consideration

It is possible, although related to a lot of development and extra code, to have a toggle to switch between white and dark mode. Here it would be important to remember the setting in the last session, which is again more code...

Let's see what the [community says](https://twitter.com/HillebrandMax/status/1157554875611398144).

**Comment by infominer33** [comment]
I think if you have such strong opinions, and you are doing the work, then just do it how you like...

**Comment by dennisreimann** [comment]
We should just leverage the [CSS `prefers-color-scheme` property](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), then we are good to go and support the users preferences. It's not much work and I can implement that later today.

**Comment by yahiheb** [comment]
To darkmode.

**Comment by dennisreimann** [comment]
I have implemented this in #53 – let's keep track of this feature request there.

**Comment by yahiheb** [comment]
Any one has an idea how to change the mode?

**Comment by dennisreimann** [comment]
Via your OS’ system preferences. That‘s a CSS based solution that uses with the OS/browser settings.
