### ISSUE TITLE
How to check and fix broken links?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#582]
Is there some useful magic to be used to automatically check if the links are still working, and if possible, automatically fix them too?

**Comment by RiccardoMasutti** [comment]
> Is there some useful magic to be used to automatically check if the links are still working, and if possible, automatically fix them too?

I take that. As soon as we implement Google Search Console, it will scan daily *.wasabiwallet.io and tell us crawl errors (broken links)

**Comment by RiccardoMasutti** [comment]
Google Search Console still not implemented. I will make a new PR on /WalletWasabi repo to add a verification file

**Comment by yahiheb** [comment]
> Google Search Console still not implemented.

Is there a PR for that?

**Comment by RiccardoMasutti** [comment]
> > Google Search Console still not implemented.
> 
> Is there a PR for that?

Tomorrow I will

**Comment by PeterXMR** [comment]
Some links still doesn't work ->
https://github.com/zkSNACKs/WasabiDoc/tree/master/docs/building-wasabi/
any update on that? I'll look on it if nobody is working on it.

**Comment by yahiheb** [comment]
The work in the docs website.
https://docs.wasabiwallet.io/building-wasabi/

**Comment by RiccardoMasutti** [comment]
@MaxHillebrand Now we receive alerts from GSC when Google crawls a 404 link/page.

**Comment by yahiheb** [comment]
> @MaxHillebrand Now we receive alerts from GSC when Google crawls a 404 link/page.

Where do we receive that?

**Comment by RiccardoMasutti** [comment]
> > @MaxHillebrand Now we receive alerts from GSC when Google crawls a 404 link/page.
> 
> Where do we receive that?

I personally reiceve them. I also added the rest of zksnacks' team as GSC administrators
