### ISSUE TITLE
CoinJoin change privacy

### ISSUE THREAD

**Issue by emma-borhanian** [zkSNACKs/WasabiDoc#640]
I'm trying to understand how to securely/privately make lots of small purchases less than 0.1 bitcoin.

e.g. If I:
* coinjoin from address A 1btc (anon 1) to address B ~0.1btc (anon 100)
* spend some of B, now B_change is no longer large enough to conjoin again
* coinjoin from address A 0.9btc (anon 1) to address C ~0.1btc (anon 100)
* spend some of C, now C_change is no longer large enough to conjoin again
* directly consolidate coinjoin from B_change and C_change to D

![change](https://user-images.githubusercontent.com/1713748/76714779-5737b000-66e6-11ea-9ab4-9d6af6e2e82b.png)

Then can people tell that both B and C came from A by looking for this diamond shape?

**Comment by MaxHillebrand** [comment]
Yes. 
The coordinator has signature proofs of both of `B_change` and `C_change`, so at least he knows exactly that both belong to the same entity.
Also, any advanced attacker can do subset sum analysis and might find out [though computationally expensive] that the two belong to each other.

**Comment by yahiheb** [comment]
Something is wrong in your example:

> coinjoin from address A 0.9btc (anon 1) to address C ~0.1btc (anon 100)

This can't be true, because after you make the first CoinJoin (to address B) the 0.9 btc left will not be on address A but rather it will be on another address.

> Yes.
> The coordinator has signature proofs of both of B_change and C_change, so at least he knows exactly that both belong to the same entity.
> Also, any advanced attacker can do subset sum analysis and might find out [though computationally expensive] that the two belong to each other.

I think this is not correct.
You can tell that they belong to the same person but you can't tell that `B_change` and `C_change` came from the same address A, they might have come from different addresses.


> Then can people tell that both B and C came from A by looking for this diamond shape?

Given that example I say you can't tell that they came from the same address, if you can then CoinJoin is broken.

**Comment by MaxHillebrand** [comment]
> You can tell that they belong to the same person but you can't tell that B_change and C_change came from the same address A, they might have come from different addresses.

This is correct. You do not know that `B_change` and `C_change` came from the `A` coin. I was initially misreading the question. What I was referring to was only that `B_change` and `C_change` can be identified [with proof for the coordinator, with computational complexity for others] to belong to the same entity.

**Comment by yahiheb** [comment]
> What I was referring to was only that B_change and C_change can be identified [with proof for the coordinator, with computational complexity for others] to belong to the same entity.

Even that is not correct.

> coinjoin from address A 1btc (anon 1) to address B ~0.1btc (anon 100)
> spend some of B, now B_change is no longer large enough to conjoin again

`B_change` and `C_change` are changes that came after spending anonymous coins (anon 100 for ex) so the coordinator can't tell they came from address A.

**Comment by MaxHillebrand** [comment]
> > What I was referring to was only that B_change and C_change can be identified [with proof for the coordinator, with computational complexity for others] to belong to the same entity.
>
> Even that is not correct.

I might be explaining it badly, but I'm pretty sure that this is correct. The Tor identity `Alice` connects to the coordinator in the [input registration phase](https://docs.wasabiwallet.io/using-wasabi/CoinJoin.html#input-registration) with a signature proof of ALL the coins [up to 7] that she wants to enqueue in this round. Yes, this does not mean that the coordinator knows that these two coins are from `Coin A`, but it does reveal the common ownership of these two coins.

**Comment by yahiheb** [comment]
Oh that is correct, I didn't understand you before, my mistake.
