### ISSUE TITLE
[FEATURE] Embeded YouTube videos

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#66]
We already have MANY amazing videos that explain the nuances of Wasabi, and we should include them in this documentation.
Right now they are only hyperlinks that lead to the external youtube site.

How can vidoes be embedded in VuePress, so that it shows the player in the docs it self?

**Comment by dennisreimann** [comment]
I did something similar in the [UIengine docs](https://uiengine.uix.space/basics/getting-started/) and can take care of that. I'd try to use the [markdown-it-video](https://github.com/CenterForOpenScience/markdown-it-video) plugin for that.
