### ISSUE TITLE
Wasabi Glossary to the website as well

### ISSUE THREAD

**Issue by Zolgarr** [zkSNACKs/WasabiDoc#680]
I was browsing through the websites:

https://wasabiwallet.io/
https://docs.wasabiwallet.io/ 

It came to me that a Definitions Dictionary would be great for the people who are not so experienced in Bitcoin in general. 
Then I've found the Glossary on GitHub and I was very happy about it.
https://github.com/zkSNACKs/WasabiDoc/tree/master/docs/glossary/

Some of the newbies might not find it though or just won't take the time to search for it.
I think it would be great if there would be a direct link to this glossary from the Wasabi website or there could also be a section on the website where the Wasabi Glossary could be found.

**Comment by MaxHillebrand** [comment]
The glossary is in the top menu bar for [the documentation](docs.wasabiwallet.io), but yes, it is not in the top menu bar of the [main website](wasabiwallet.io). However, the main website does link to the docs, where then the reader will find the glossary too. I'm not sure if we should clutter the main website with the glossary too...

**Comment by Zolgarr** [comment]
Hmmm I feel you, makes sense.

**Comment by Zolgarr** [comment]
Since I failed to find the glossary in the documentation (somehow I missed it but I suppose if I missed it then it might happen to others too) I thought about something else. Would it be possible to make the top menu bar of the documentation bigger so that it's more visible?

**Comment by Zolgarr** [comment]
Another thing that came to my mind: 
I'd suggest to merge the two parts of the glossary in the documentation: "Bitcoin in general" and 
"Privacy and Wasabi" since people will most probably be looking for specific words through ctrl+F and it would be easier in my opinion if the glossary would be in one part instead of two.

**Comment by MaxHillebrand** [comment]
@Zolgarr the glossary is ment to be used with the in-built search function, at the top right of the website, and not necessarily with `ctrl+F`.

**Comment by Zolgarr** [comment]
@MaxHillebrand oh I see, I didn't think about that at all. Also, the in-built searches on websites for me so far were kind of useless, so I thought about ctrl+F right away, not even considering the in-built search.

**Comment by MaxHillebrand** [comment]
We use Algolia, which is a very advanced and well indexed search function - it works very well, imo.

**Comment by Zolgarr** [comment]
I see, sounds good.
