### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Zolgarr** [zkSNACKs/WasabiDoc#687]
I'm still inexperienced in using GitHub so I'm not sure if this is the right place for me to post it. If not, please guide me to the appropriate place.

1. In the documentation at the "Why Wasabi" section in the last sentence, there's a typo:
It's self-defense instead of self defense.

2. Also, the same thing at the "Why privacy is important" section in the last sentence of the paragraph under the video. 

3. At the section "Why financial privacy is especially important" in the part "pseudonyms protect your identity in bitcoin" at the last sentence a comma is not needed:

This clearly makes no sense and has potentially dangerous ramifications. 
Instead of "This clearly makes no sense, and has potentially dangerous ramifications."

**Comment by yahiheb** [comment]
> I'm still inexperienced in using GitHub so I'm not sure if this is the right place for me to post it. If not, please guide me to the appropriate place.

It would be even better if you clone the WasabiDoc repo and make a pull request.
Take a loot at this https://www.youtube.com/watch?v=rgbCcBNZcdQ
