### ISSUE TITLE
Expanding the glossary

### ISSUE THREAD

**Issue by Zolgarr** [zkSNACKs/WasabiDoc#691]
As I was reading through the documents I thought I'd add some words which are not in the glossary so far and it would be useful for a newbie. Note: I'd add such words too which might be very basic for developers but for newcomers, it would be nice to have a clear and simple explanation and understanding for it.

Here are my suggestions for the glossary:
-Bitcoin
-Plausible deniability

**Comment by MaxHillebrand** [comment]
Sure, good idea.
Best to open a pull request with the explanation of these words directly.
