### ISSUE TITLE
How to format images?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#70]
How can I format the position of a picture?
For example, how can it be nested on the side of a paragraph with breaking lines at the boarders?

**Comment by dennisreimann** [comment]
Do you have any examples for images you‘d like to format specifically?

**Comment by MaxHillebrand** [comment]
For example in the installation instruction, there is a picture of the new website download icon, this is a rather small image, and I think it would be nice to nest it on the right / left side of a paragraph with wrapped lines.

**Comment by MaxHillebrand** [comment]
we got all the images in `/.vuepress/public/` in `.png` format.
