### ISSUE TITLE
[BUG] Sidebar Depth FAQ

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#71]
the `config.js` file has `sidebarDepth: 2` for all the pillars, including the FAQ, I also tested with adding this header to the FAQ files:
```
---
sidebarDepth: 2
---
```
But regardless, the [FAQ-Contribution.md](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/FAQ/FAQ-Contribution.md), [FAQ-Installation.md](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/FAQ/FAQ-Installation.md), [FAQ-Introduction.md](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/FAQ/FAQ-Introduction.md) files do not show the headers with `##` or `###` in the sidebar.

This bug comes up when there are only `#` and `###` headers in the file, and no `##` headers. Thus it can be fixed when adding at least one `##` headers to the file. Yet is there a proper fix so that it does diplay `###` headers when there are no `##` headers?

**Comment by MaxHillebrand** [comment]
https://github.com/zkSNACKs/WasabiDoc/commit/18ca45ccde1415a45fbdb90bf6d0fcc7163a3b34 this adds `##` headers to the above mentioned files, and thus fixes the bug - but only kind-off, and not properly.

**Comment by dennisreimann** [comment]
This seems to be a bug and it affects the table of contents as well. Seems like something in the VuePress internal data structure requires a proper heading level incrementation.

**Comment by MaxHillebrand** [comment]
Something that we [haha, you] can fix, or is this a bug for upstream?

**Comment by dennisreimann** [comment]
This should be done upstream. I found this issue which describes the bug: vuejs/vuepress#1399

**Comment by MaxHillebrand** [comment]
Although the underlying bug is still present, because we now use the `##` headers as well, it is no longer present in this repo.
There might be some new issues regarding #79, but that might not be merged at all...

Thus, closing this issue.
