### ISSUE TITLE
[FEATURE] drop-down for FAQ

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#72]
Is there a way to add a drop down text box?

This might be useful for the FAQ. All questions are displayed in a single line, each has a drop down arrow, and when clicked it reveals the answer to the question. Somewhat similar to how the [new wasabiwallet.io](https://www.weareblock.space/wasabi/) does the FAQ. This would make the `[[toc]]` obsolete.

**Comment by dennisreimann** [comment]
Yes, we can add something similar to the tip/warning/danger custom blocks and use the HTML [details disclosure tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) for the output.
