### ISSUE TITLE
Publish a documentation book

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#731]
This is more of a fun idea rather than a serious roadmap, but why not...?

Let's publish a paper book with the documentation to gift / sell to users!

Pro:
- fun
- throwback to the good old days with paper handbook documentation
- incentive to re-work and re-edit docs

Con:
- Cannot be updated [maybe future versions / editions?]
- Lot's of work

**Comment by RiccardoMasutti** [comment]
I don't think is a good idea but I can follow and help in this. I've got huge experience in book publishing. Last year I published italian translation of Mastering Bitcoin and atm I'm working on porting paper version of the italian translation of Bitcoin Standard to ebook.

Ps: it's not true we can't update the paper book. We can with print on demand.

Let's discuss it in Slack

**Comment by MarnixCroes** [comment]
Won't happen. closing
