### ISSUE TITLE
Opening XAML files with VS2019 Pro Edition

### ISSUE THREAD

**Issue by hgmamaci** [zkSNACKs/WasabiDoc#784]
I cannot view XAML files, it alerts as if some references are missing. Though all references are up to date and there are no warnings. I can also build the complete solution without problems. It is only that I cannot view XAML visually.

I am using VS 2019 PRO on Windows 10 Pro X64.

Sorry. I couldn't find any blog to post his issue.
![XAML issue](https://user-images.githubusercontent.com/3295186/80283518-d2967380-8720-11ea-9701-0d3a2b1e6a8c.png)

**Comment by MaxHillebrand** [comment]
It seems that you are trying to open a XAML file of the main wallet?
Then it would be better to open this issue [in the main repo](https://github.com/zksnacks/walletwasabi/issues/new).

I have no clue why it doesn't work for you...

**Comment by yahiheb** [comment]
@nopara73 @danwalmsley

**Comment by danwalmsley** [comment]
Install Avalonia plugin and you need to build the project for the previewer to work.

**Comment by yahiheb** [comment]
You mean this? https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio

**Comment by hgmamaci** [comment]
I did but now I get following error and opened a new issue as you suggested on the main repo

09:49:18.623 [Information] 0 Starting previewer process for '"D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\bin\Debug\netcoreapp3.1\WalletWasabi.Gui.dll"'
09:49:18.626 [Information] 23404 Started previewer process for '"D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\bin\Debug\netcoreapp3.1\WalletWasabi.Gui.dll"'. Waiting for connection to be initialized.
09:49:18.776 [Information] 23404 Connection initialized
09:49:19.762 [Error] 23404 <= "Unhandled exception. Unhandled exception. System.InvalidOperationException: Call from invalid thread"
09:49:19.763 [Error] 23404 <= "   at Avalonia.Threading.Dispatcher.VerifyAccess()"
09:49:19.764 [Error] 23404 <= "   at Avalonia.AvaloniaObject.VerifyAccess()"
09:49:19.765 [Error] 23404 <= "   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)"
09:49:19.766 [Error] 23404 <= "   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority)"
09:49:19.767 [Error] 23404 <= "   at Avalonia.Controls.TextBox.set_PasswordChar(Char value)"
09:49:19.768 [Error] 23404 <= "   at WalletWasabi.Gui.Controls.TogglePasswordBox.<.ctor>b__1_2(Boolean x) in D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\Controls\TogglePasswordBox.cs:line 29"
09:49:19.769 [Error] 23404 <= "   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 44"
09:49:19.770 [Error] 23404 <= "   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 740"
09:49:19.787 [Error] 23404 <= "   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 685"
09:49:19.789 [Error] 23404 <= "   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\DefaultScheduler.cs:line 182"
09:49:19.789 [Error] 23404 <= "   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ConcurrencyAbstractionLayerImpl.cs:line 76"
09:49:19.790 [Error] 23404 <= "   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)"
09:49:19.790 [Error] 23404 <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:19.791 [Error] 23404 <= "--- End of stack trace from previous location where exception was thrown ---"
09:49:19.791 [Error] 23404 <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:19.792 [Error] 23404 <= "   at System.Threading.ThreadHelper.ThreadStart(Object obj)"
09:49:19.793 [Error] 23404 <= "System.InvalidOperationException: Call from invalid thread"
09:49:19.793 [Error] 23404 <= "   at Avalonia.Threading.Dispatcher.VerifyAccess()"
09:49:19.794 [Error] 23404 <= "   at Avalonia.AvaloniaObject.VerifyAccess()"
09:49:19.794 [Error] 23404 <= "   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)"
09:49:19.795 [Error] 23404 <= "   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority)"
09:49:19.795 [Error] 23404 <= "   at WalletWasabi.Gui.Controls.TogglePasswordBox.set_IsPasswordVisible(Boolean value) in D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\Controls\TogglePasswordBox.cs:line 37"
09:49:19.796 [Error] 23404 <= "   at WalletWasabi.Gui.Controls.TogglePasswordBox.<.ctor>b__1_0(Boolean x) in D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\Controls\TogglePasswordBox.cs:line 25"
09:49:19.798 [Error] 23404 <= "   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 44"
09:49:19.799 [Error] 23404 <= "   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 740"
09:49:19.799 [Error] 23404 <= "   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 685"
09:49:19.801 [Error] 23404 <= "   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\DefaultScheduler.cs:line 182"
09:49:19.802 [Error] 23404 <= "   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ConcurrencyAbstractionLayerImpl.cs:line 76"
09:49:19.815 [Error] 23404 <= "   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)"
09:49:19.819 [Error] 23404 <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:19.820 [Error] 23404 <= "--- End of stack trace from previous location where exception was thrown ---"
09:49:19.821 [Error] 23404 <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:19.822 [Error] 23404 <= "   at System.Threading.ThreadHelper.ThreadStart(Object obj)"
09:49:26.040 [Error] 23404 <= "Unhandled exception. System.InvalidOperationException: Call from invalid thread"
09:49:26.042 [Error] 23404 <= "   at Avalonia.Threading.Dispatcher.VerifyAccess()"
09:49:26.043 [Error] 23404 <= "   at Avalonia.AvaloniaObject.VerifyAccess()"
09:49:26.044 [Error] 23404 <= "   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)"
09:49:26.046 [Error] 23404 <= "   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority)"
09:49:26.046 [Error] 23404 <= "   at WalletWasabi.Gui.Controls.TogglePasswordBox.set_IsPasswordVisible(Boolean value) in D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\Controls\TogglePasswordBox.cs:line 37"
09:49:26.047 [Error] 23404 <= "   at WalletWasabi.Gui.Controls.TogglePasswordBox.<.ctor>b__1_0(Boolean x) in D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\Controls\TogglePasswordBox.cs:line 25"
09:49:26.048 [Information]  Process exited
09:49:26.048 [Information]  Stopping previewer process
09:49:26.048 [Error]  <= "   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 44"
09:49:26.051 [Error]  <= "   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 740"
09:49:26.052 [Error]  <= "   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 685"
09:49:26.052 [Error]  <= "   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\DefaultScheduler.cs:line 182"
09:49:26.053 [Error]  <= "   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ConcurrencyAbstractionLayerImpl.cs:line 76"
09:49:26.053 [Error]  <= "   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)"
09:49:26.054 [Error]  <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:26.054 [Error]  <= "--- End of stack trace from previous location where exception was thrown ---"
09:49:26.054 [Error]  <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:26.055 [Error]  <= "   at System.Threading.ThreadHelper.ThreadStart(Object obj)"
09:49:26.055 [Error]  <= "Unhandled exception. System.InvalidOperationException: Call from invalid thread"
09:49:26.056 [Error]  <= "   at Avalonia.Threading.Dispatcher.VerifyAccess()"
09:49:26.057 [Error]  <= "   at Avalonia.AvaloniaObject.VerifyAccess()"
09:49:26.057 [Error]  <= "   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)"
09:49:26.057 [Error]  <= "   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority)"
09:49:26.058 [Error]  <= "   at Avalonia.Controls.TextBox.set_PasswordChar(Char value)"
09:49:26.058 [Error]  <= "   at WalletWasabi.Gui.Controls.TogglePasswordBox.<.ctor>b__1_2(Boolean x) in D:\Yazilim\Bitcoin\WalletWasabi\WalletWasabi.Gui\Controls\TogglePasswordBox.cs:line 29"
09:49:26.059 [Error]  <= "   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 44"
09:49:26.059 [Error]  <= "   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 740"
09:49:26.060 [Error]  <= "   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 685"
09:49:26.060 [Error]  <= "   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\DefaultScheduler.cs:line 182"
09:49:26.060 [Error]  <= "   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\ConcurrencyAbstractionLayerImpl.cs:line 76"
09:49:26.061 [Error]  <= "   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)"
09:49:26.061 [Error]  <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:26.062 [Error]  <= "--- End of stack trace from previous location where exception was thrown ---"
09:49:26.062 [Error]  <= "   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
09:49:26.062 [Error]  <= "   at System.Threading.ThreadHelper.ThreadStart(Object obj)"
