### ISSUE TITLE
Headlines on the side on WasabiDocs

### ISSUE THREAD

**Issue by Zolgarr** [zkSNACKs/WasabiDoc#791]
When I was reading through `WasabiDocs` at the `Why Wasabi` main heading it was a bit frustrating for me that on the left side when I clicked on `CoinJoin Legal Concern` the list was really long and at first I couldn't decide which ones still belong to the `CoinJoin Legal Concern` and which ones belong to the next heading. Also, there's no difference in the font of the subheadings and the headings, only the main headings are **bold**.

My suggestion would be that the main headings (`Why Wasabi`, `Privacy in Bitcoin` etc.) could be bigger and/or with another color), the headings (`Why Privacy is Important`, `CoinJoin Legal Concern`, etc) could be **bold** and when you click on one the list comes down, and when you click on that again it goes back. To make it even more clear (but I'd say after the latter is done this is optional): the subheadings (`Overview`, `CoinJoin Transactions`, etc) could be a bit farther away to the right from the headings so that it's more distinguishable.

**Comment by yahiheb** [comment]
> Also, there's no difference in the font of the subheadings and the headings, only the main headings are bold.

> My suggestion would be that the main headings (Why Wasabi, Privacy in Bitcoin etc.) could be bigger and/or with another color), the headings (Why Privacy is Important, CoinJoin Legal Concern, etc) could be bold

They are already as you suggested:

![Capture](https://user-images.githubusercontent.com/52379387/80425751-96ac0b80-88e4-11ea-953b-1c56b3c733a9.PNG)
![Capture1](https://user-images.githubusercontent.com/52379387/80425759-9ad82900-88e4-11ea-9315-cc465b3f861d.PNG)

> and when you click on one the list comes down, and when you click on that again it goes back.

ACK

**Comment by Zolgarr** [comment]
In my opinion, they are not. You might say that because that's sufficient for you. But as I was seeing it with a kind of a new user's perspective, it's not distinguishable enough. The headings are not bold, they have the same font as the subheadings. And the subheadings should be several spaces to the right in my opinion.
I'm still saying it should be more clear, repeating what I wrote above:

My suggestion would be that the main headings (Why Wasabi, Privacy in Bitcoin etc.) could be bigger and/or with another color), the headings (Why Privacy is Important, CoinJoin Legal Concern, etc) could be bold and when you click on one the list comes down, and when you click on that again it goes back. To make it even more clear (but I'd say after the latter is done this is optional): the subheadings (Overview, CoinJoin Transactions, etc) could be a bit farther away to the right from the headings so that it's more distinguishable.

**Comment by Zolgarr** [comment]
Any other comments?

**Comment by Zolgarr** [comment]
Isn't the option easier what I recommended? Just changing the font would be a huge improvement in my opinion.

**Comment by MarnixCroes** [comment]
@CAnorbo what do you think?
Any room for improvement?

**Comment by CAnorbo** [comment]
> @CAnorbo what do you think?
> Any room for improvement?

Is it still an issue? Since we updated the docs a year ago I think it fixed this one.

**Comment by MarnixCroes** [comment]
> > @CAnorbo what do you think?
> > Any room for improvement?
> 
> Is it still an issue? Since we updated the docs a year ago I think it fixed this one.

the layout is still the same, right

**Comment by MarnixCroes** [comment]
@CAnorbo if you don't see an obvious improvement, let's close it
