### ISSUE TITLE
How to acknowledge contributors?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#8]
This is an open source archive of knowledge, and the goal is to have both users and developers collaborate to ensure that Wasabi is properly explained. We already have many contributions [for example the FAQ], and we will continue to see new peers joining the effort.

### The question is

How do we properly attribute and thank the creators of the specific information?

Git helps here a lot, it's clear who has done what commit. However, for example the FAQ was written by several others, yet I committed it to this new repository, thus obfuscating who actually created it.

I don't think it is a good idea to have attribution directly in the doc, meaning that every line has a footnote with whom has written it. This will clutter the doc and GitBook.

How about we have a separate file that lists all the contributors, we could maybe link to the specific contributions they've made, but that will be a pain to keep up to date...

Ultimately, I'm not sure, so this issue is open to start the conversation :)

**Comment by raindogdance** [comment]
I am neither very experienced with Git/GitBook/GitHub nor with open source contribution in general, so take my opinion with a grain of salt :)  

I think it would be nice to have a line somewhere mentioning all contributors, but it's not necessary to mention the specific commits etc. Perhaps something like: "This documentation was created with the help of the following contributors: [...]" is sufficient.  

Alternatively, an extra page in the doc with the mentions of the contributors nicks and links to either their Twitter or GitHub repo or some project of theirs.

**Comment by dennisreimann** [comment]
[All Contributors](https://github.com/all-contributors/all-contributors) might be an option here :)

**Comment by MaxHillebrand** [comment]
I guess this will be an entire re-imagination of the [dojo](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/building-wasabi/Dojo.md)...

All-Contributors looks good.

**Comment by dennisreimann** [comment]
I tried it with a personal project and IMHO this is a great fit. Especially since it is very easy to [mark contributors in issues and pull requests]( https://allcontributors.org/docs/en/bot/usage) and also note what they contributed. 👍

The initial setup is easy and after that you can start tagging people as contributors right away. The bot then opens a PR that adds the person to the list in the README. 👌

**Comment by MaxHillebrand** [comment]
I like this!
But I don't think it's good to add all the dependencies [chat bot and such] to the main repo, but there should not be many security concerns to have it in the docs repo?
But then we could not use the chat bot on issues of the main repo, and if we'd like to add a contributor, we'd have to open a new issue / pr in the docs repo? I don't think this would be too bad, but would take away some of the UX of the bot.

**Comment by MaxHillebrand** [comment]
I have [opened a new thread](https://discourse.sourcecred.io/t/wasabi-wallet-documentation/139) on the [SourceCred](https://sourcecred.io) forum to see how we might use their tool to find out the quantity and quality of contributions!

**Comment by MaxHillebrand** [comment]
@all-contributors please add @dennisreimann for design

**Comment by MaxHillebrand** [comment]
This setup was ridiculously easy...
Let's make sure that everything is added properly.

I think this should also be added to the dojo!

**Comment by dennisreimann** [comment]
I have added it to the Dojo, but I think we'll need some manual adjustments there. That's because we will need separate lists (for the different belts) rather than a general list. Nevertheless, I can tweak this once we add some more people to the list :)

Other than that this is good to go I think…

**Comment by dennisreimann** [comment]
@all-contributors please add @MaxHillebrand for content, doc, example, maintenance, projectManagement, review, video.

@all-contributors please add @thunderBiscuit for ideas.

@all-contributors please add @mayankchhabra for design.

**Comment by dennisreimann** [comment]
@all-contributors please add @MaxHillebrand for content, doc, example, maintenance, projectManagement, review and video.

**Comment by dennisreimann** [comment]
@all-contributors please add @thunderBiscuit for ideas.

**Comment by dennisreimann** [comment]
@all-contributors please add @mayankchhabra for design.

**Comment by MaxHillebrand** [comment]
@all-contributors please add @6102bitcoin for idea and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @nopara73 for code idea maintenance review and talk

**Comment by MaxHillebrand** [comment]
@all-contributors please add @molnard for blog code review and maintenance

**Comment by MaxHillebrand** [comment]
@all-contributors please add @lontivero for code review maintenance and projectManagement

**Comment by MaxHillebrand** [comment]
@all-contributors please add @NicolasDorier for code ideas review

**Comment by MaxHillebrand** [comment]
@all-contributors please add @benthecarman for code bug review and design

**Comment by MaxHillebrand** [comment]
@all-contributors please add @yahiheb for code review test and bug

**Comment by MaxHillebrand** [comment]
@all-contributors please add @danwalmsley for code review design idea and test

**Comment by MaxHillebrand** [comment]
@all-contributors please add @varsnotwars for code

**Comment by MaxHillebrand** [comment]
@all-contributors please add @jmacato for code

**Comment by MaxHillebrand** [comment]
@all-contributors please add @jmacato for code

**Comment by MaxHillebrand** [comment]
@all-contributors please add @zolgarr for content doc video and tutorial

**Comment by MaxHillebrand** [comment]
@all-contributors please add @raindogdance for tutorial doc content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @wintercooled for doc and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @mixelated for doc and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @Mixelated for doc and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @francispouliot for business and ideas

**Comment by MaxHillebrand** [comment]
@all-contributors please add @xavierfiechter for docs and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @gugero for code and bugs

**Comment by MaxHillebrand** [comment]
@all-contributors please add @guggero for code and bug

**Comment by MaxHillebrand** [comment]
@all-contributors please add @AdamISZ for idea example and review

**Comment by MaxHillebrand** [comment]
@all-contributors please add @chris-belcher for idea example and review

**Comment by MaxHillebrand** [comment]
Sorry for spamming you all with this huge tread...

But now that I have you all together, I want to sincerely THANK YOU ALL for your invaluable contributions to this libre & open source projects. You all are heroes of Bitcoin privacy, and I hold your support in very high regard!

**Comment by MaxHillebrand** [comment]
@all-contributors please add @RiccardoMasutti for docs and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @CryptoRafe for docs and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @kravens for docs and content

**Comment by MaxHillebrand** [comment]
@all-contributors please add @michaeltoth  for docs and content

**Comment by chris-belcher** [comment]
Please don't use my name to promote Wasabi wallet. Remove it from this list. Thanks.

**Comment by lontivero** [comment]
@MaxHillebrand what is the criteria for adding people to this list? I ask this because if well it is true that we all learn and get technical feedback from others, I didn't find any github issue, pull request, commit, content or any other material from @chris-belcher related to Wasabi so, yes, it looks like we are using his name to promote Wasabi.  

@chris-belcher our apologies, this was not our intention, we are going to revert this asap.

**Comment by MaxHillebrand** [comment]
Sorry @chris-belcher, it's not my intention to mis-represent you, the commit is already reverted [here](2f27c4ae690d37f90aebd129d5e8e382f42b8b47).

@lontivero, All-Contributors is designed to acknowledge literally ALL the peers who have supported Wasabi, not just those who code [they are already [here](https://github.com/zkSNACKs/WalletWasabi/graphs/contributors)]. You can find a list of all the default categories of support [ħere](https://allcontributors.org/docs/en/emoji-key), as you see, it includes those with high level ideas [like Belcher], asking good questions, or managing the finances of a project. 

So at first, we will go by these labels to thank all the supporters. But we are also thinking of how to integrate with the belt logic of the Wasabi dojo. So this is a work in progress and open for review and improvements.
