### ISSUE TITLE
Was this site useful survey?

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#806]
The [BTCPay docs](https://docs.btcpayserver.org/) have a survey at the bottom of every chapter if the page was useful.
![screenshot_20200502_103742](https://user-images.githubusercontent.com/30683012/80859405-1299b100-8c61-11ea-9e36-bed75cb9cf8f.png)

The questions I have...

- For what is this information used?
- How are the answers analysed?
- Is this useful for Wasabi docs too?

[cc @britttttk @kukks @pavlenex @dennisreimann]

**Comment by pavlenex** [comment]
Honestly I don't remember us ever looking at that data. We get live-feedback from people on our community chat. Raised this question [here](https://github.com/btcpayserver/btcpayserver-doc/issues/495). I guess it can be useful for some people, but we get plenty of feedback that' more relevant from real-time communication from actual users.  It's handled by a third-party (GitBook).

**Comment by dennisreimann** [comment]
I agree with @pavlenex that actual user feedback beyond a simple rating is required to take any action.

**Comment by MaxHillebrand** [comment]
Alright, I agree. 
Thanks for providing the feedback!
