### ISSUE TITLE
Headlines missing on the left side of Docs with IE

### ISSUE THREAD

**Issue by BTCparadigm** [zkSNACKs/WasabiDoc#814]
Even though nobody should use Internet Explorer, I did, and the docs.wasabiwallet.io page seemed to show up incorrectly. 
Most of the headlines are missing.
I haven't seen this problem with other browsers.

![photo_2020-05-07_15-12-20](https://user-images.githubusercontent.com/51679301/81331902-f2c41c00-90aa-11ea-8bf5-c21dc80b55f2.jpg)

**Comment by RiccardoMasutti** [comment]
I can reproduce with IE 9,10 and 11.

I'm still investigating, seems like a css trasparency bug

**Comment by RiccardoMasutti** [comment]
Can you please test it without dark/night mode?

**Comment by RiccardoMasutti** [comment]
@dennisreimann @yahiheb @MaxHillebrand you can test with https://www.browserling.com/internet-explorer-testing

**Comment by dennisreimann** [comment]
All of the mentioned Internet Explorer versions are outdated and not supported by Microsoft anymore. I wouldn‘t care about that.

**Comment by RiccardoMasutti** [comment]
> All of the mentioned Internet Explorer versions are outdated and not supported by Microsoft anymore. I wouldn‘t care about that.

I agree with you. @BTCparadigm what IE version are you using?

**Comment by BTCparadigm** [comment]
Oh, my bad, I didn't realize those IE versions are outdated and not supported my Microsoft anymore. 
I can't check the version at the moment, since it was on a computer that I don't have access right now. 
In 2 days I'll get back to work and I'll let you guys know.

**Comment by BTCparadigm** [comment]
Sorry guys, I totally forgot about this. 
It was IE 11.
