### ISSUE TITLE
Issue in send request

### ISSUE THREAD

**Issue by SnpGroup** [zkSNACKs/WasabiDoc#816]
I am sending send request as per mentioned RPC format 

curl -s --data-binary '{"jsonrpc":"2.0","id":"1","method":"send", "params": { "payments":[ {"sendto": "tb1qgvnht40a08gumw32kp05hs8mny954hp2snhxcz", "amount": 15000, "label": "David" } ], "coins":[{"transactionid":"ab83d9d0b2a9873b8ab0dc48b618098f3e7fbd807e27a10f789e9bc330ca89f7", "index":0}], "feeTarget":2, "password": "password1234" }}' http://127.0.0.1:37128/

I have replaced sendto, amount, label, transactionid and password as per my specific values.

Here transaction id is used from unspentcoins list, but my request is getting failed with following error.

"error": {
"code": -32603,
"message": "Needed: 0.0000001 BTC, got only: 0.00 BTC."
}

please guide me, i am stuck with my development

thanks

**Comment by yahiheb** [comment]
> "message": "Needed: 0.0000001 BTC, got only: 0.00 BTC."

From that error message it looks like you don't have bitcoin.

**Comment by SnpGroup** [comment]
Somehow document is not clear enough atleast for me. I am using lot of assumptions while sending curl request. 

I have enough BTC in my wallet 0.11.....I have to send 15 dollars, what should go in amount 15 or 1500. When I am giving feetarget 2, i am getting different error ""message": "The transaction fee is more than twice the sent amount: 653.2%."

**Comment by yahiheb** [comment]
@lontivero Can you take a look at this?

> I have to send 15 dollars, what should go in amount 15 or 1500.

The amount should be in sat (satoshi) not in USD.

**Comment by SnpGroup** [comment]
Thanks a lot for quick response.

I tried sending 101550 satoshi, which is equivalent to 10 USD, it's got transferred successfully.

I would suggest to add this information in document, as first timer will not have any clue what should go there.

Thanks a lot

**Comment by SnpGroup** [comment]
Also please clarify what is mean by feetarget: 2......fee charged 1.29 USD for 10 USD, which is too high.

**Comment by MaxHillebrand** [comment]
Regarding the fee target, it is Bitcoin Core's `Smart Fee` algorithm. 
read more about it [here](https://bitcointechtalk.com/an-introduction-to-bitcoin-core-fee-estimation-27920880ad0)

**Comment by SnpGroup** [comment]
You can close issue #816.

My send request is working now.

I suggest to update document to mention what each values stands for.

Thanks for your quick support.

**Comment by yahiheb** [comment]
Thank you.

**Comment by yahiheb** [comment]
> I suggest to update document to mention what each values stands for.

Thank you for your suggestion, the RPC is meant to be used by power users and they should be familiar with those values.
