### ISSUE TITLE
Query on coinjoin

### ISSUE THREAD

**Issue by SnpGroup** [zkSNACKs/WasabiDoc#834]
How I can achive coinjoin efficiently if I have 10 BTC in my wallet in one go?

Currently if I have 1 BTC and I do coinjoin, it does coinjoin for 0.12 btc and remaining balance remains as is.

**Comment by yahiheb** [comment]
Take a look at the following threads:
https://www.reddit.com/r/WasabiWallet/comments/dp271q/is_it_cheaper_to_mix_a_big_amount_rather_than_a/

https://www.reddit.com/r/WasabiWallet/comments/fl0rot/cost_of_wasabi_for_10btc_eg/

https://www.reddit.com/r/WasabiWallet/comments/eowfrt/how_long_should_it_take_to_coinjoin_1_btc_10btc/

https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-are-the-equal-denominations-created-in-one-mixing-round

https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#what-are-the-fees-for-the-coinjoin

**Comment by MaxHillebrand** [comment]
I am currently working with a user on writing a detailed guide on doing CoinJoin with larger amounts.

This might be one of the first posts on the new blog, I don't think it is good to put this here in the docs...

But so you know, there's something coming soonish.

**Comment by SnpGroup** [comment]
As per one of link provided by you....approx time required to coinjoin btc will as below -

~8 hours for 1 btc
~3 days for 10 btc
~1 month for 100 btc
~10 months for 1000 btc

1 month for 100 btc is too much time......we will have a requirement to coinjoin 100 btc in 1 day.

How we can achieve this?

**Comment by MaxHillebrand** [comment]
In the very first round, you will receive equal value outputs, that all have different anonset values depending on the usage of other peers at that time. 

`0.1 + 0.2 + 0.4 + 0.8 + 1.6 = 3.1`

1.6 is sometimes in the mix, sometimes it is even 3.2 too, but rarely. 

However, the high pools, like 1.6 will have rather small anonset, of maybe 5 or so. If your anonset target is 100, then this means you will have to re-mix the 1.6 again, which will break down into `0.1 + 0.2 + 0.4 + 0.8 + 0.099 = 1.59` [minus fee]. 

So, yes, if you want high anonset, then you will need to be patient.

Especially considering that your true privacy will further increase when you do random time staggered remixes, so if there are 25 coinjoins a day, you are only part of 10, randomly chosen.

Anyhow, this is not really a topic best discussed in this github issue. Please hit me up in DM and we can talk there more. Thanks.

**Comment by yahiheb** [comment]
@RiccardoMasutti it would be nice to give a reason to closing issues.
