### ISSUE TITLE
can I fix fee while sending money?

### ISSUE THREAD

**Issue by SnpGroup** [zkSNACKs/WasabiDoc#885]
I want to send money using 2 fee structure.....regular & priority.

In case of regular, I want to fix fee to 1$ and in case of priority, I want to fix fee to 5$.

How I can achieve this?

**Comment by yahiheb** [comment]
I am not aware of a way to do that.

Note that this repository is for Wasabi documentation so it would be better if you ask your question on reddit https://www.reddit.com/r/WasabiWallet/ or if you have an issue you can ask on the main repository https://github.com/zkSNACKs/WalletWasabi
