### ISSUE TITLE
Rehashing an old issue

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/WasabiDoc#893]
We recently had a doc stabilization effort that didn't go very far and some people, including me are increasingly frustrated by it. For example someone, who I will not disclose who, reported this line:

> These two tools can be combined in great effect, thus it is on the long term road-map to implement JoinMarket functionality in Wasabi Wallet.

This is an obvious mischaracterization of the truth. It came up as an idea, but it is very far from being "on the roadmap" and whoever did this knew this in the moment of writing down these lines. Why is a chapter of wishful thinking on JoinMarket in the Wasabi docs anyway?

Nevertheless, this issue isn't about the above example, that's just an illustration, but it is rather about the broader topic. Thus I'd like to hear your ideas on how to ensure the integrity and authenticity of the docs without drastic measures?

**Comment by RiccardoMasutti** [comment]
Might be related to https://github.com/zkSNACKs/WasabiDoc/pull/315

**Comment by MarnixCroes** [comment]
This can be closes, right?
