### ISSUE TITLE
Links don't open the desired section

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#912]
I don't know why but I noticed that sometimes opening a link doesn't get you to the desired section.
For example the following link should take you to the `CONNECTING COLDCARD VIA SD CARD` section but it doesn't
https://docs.wasabiwallet.io/using-wasabi/ColdWasabi.html#connecting-coldcard-via-sd-card

**Comment by MaxHillebrand** [comment]
I could not reproduce with the provided link.

**Comment by yahiheb** [comment]
On Firefox everything is working, but on Chrome I can reproduce the issue.

**Comment by RiccardoMasutti** [comment]
Yeah it also happens to me sometimes.

**Comment by yahiheb** [comment]
This is now fixed.
