### ISSUE TITLE
Bech32 address in listKeys RPC response

### ISSUE THREAD

**Issue by just-alexander** [zkSNACKs/WasabiDoc#927]
Currently, the following structure is returned in listKeys RPC response list:

{
      "fullKeyPath": "84'/0'/0'/0/1",
      "internal": false,
      "keyState": 1,
      "label": "Adam",
      "p2wpkhScript": "0 09f4ef9a012844a875222fb08fba86219d181b63",
      "pubkey": "03d02d5985dd48880edccc992b6d77584e7b68ad9b099b8e33d60a703ac0cbded7",
      "pubKeyHash": "09f4ef9a012844a875222fb08fba86219d181b63"
 }

A bitcoin address corresponding to a specific key can be added since the fullKeyPath is defined.

**Comment by just-alexander** [comment]
wrong project

**Comment by MaxHillebrand** [comment]
ftr, moved to https://github.com/zkSNACKs/WalletWasabi/issues/4247

thanks for reporting @just-alexander
