### ISSUE TITLE
Transactions broadcasted not detected in Mempool

### ISSUE THREAD

**Issue by pavaopahljina** [zkSNACKs/WasabiDoc#953]
Hey!

Don't know if this is the best place to do this, but I'll try anyway. Another thread is on Reddit.

An hour ago I sent 2 transactions to 2 different addresses, and both of them normally broadcasted within Wasabi GUI, but I can't see them on the block explorer. Is there something I can do to fix this?

Thanks!

**Comment by RiccardoMasutti** [comment]
https://www.reddit.com/r/WasabiWallet/comments/jjkstl/broadcasted_2_transactions_but_cant_see_them_in/

Replied in the thread.
