### ISSUE TITLE
tor is not running / doesn't seem to work

### ISSUE THREAD

**Issue by DamageIncorporated** [zkSNACKs/WasabiDoc#963]
I run Wasabi on on Kubuntu 20.10 and have  Tor installed and running as a system service on port 9050. 

That seems to cause a conflict with the internal Tor implementation of Wasabi.

Wasabi only connects when I turn Tor off in the settings. 
I've had a look into the tor log file "File -> Open -> Tor logfile" but there is no entry for today, when I encountered this problem so I didn't look any further.

If there's additional debug info I can provide please let me know (and ideally explain how to do that), I'm willing to do my best to help debug this issue :)

**Comment by RiccardoMasutti** [comment]
This is the documentation repo. Please report it via https://github.com/zkSNACKs/WalletWasabi/issues or  https://www.reddit.com/r/WasabiWallet.

**Comment by DamageIncorporated** [comment]
Maybe this is a greater tor issue and not related to wasabi?
I just got another message in the Bisq Keybase chat:

There have been Tor issues over the past hours. Not sure if they are resolved but some nodes seem to be still affected
https://consensus-health.torproject.org/
https://www.reddit.com/r/TOR/
"The entire Tor v3 consensus is down
All v3 onion addresses are unavailable."

**Comment by DamageIncorporated** [comment]
> This is the documentation repo. Please report it via https://github.com/zkSNACKs/WalletWasabi/issues or https://www.reddit.com/r/WasabiWallet.

Ooops, sorry! I'll fix that :-/

**Comment by molnard** [comment]
It is an issue in the Tor network - https://twitter.com/torproject/status/1348416870249074688
