### ISSUE TITLE
misleading error message when trying to send funds while not connected

### ISSUE THREAD

**Issue by DamageIncorporated** [zkSNACKs/WasabiDoc#964]
This is related to issue #963 .

I didn't notice that tor and the backend where not connected when I tried to make a payment today. 

When trying to send, I got an error message concerning the fee, I think it said "invalid fee rate".  That was a misleading message as the real problem seems to be that wasabi was not connected at all.
 
After playing with fee values and trying to select different coins, I finally became aware that wasabi (tor and backend) was not connected .

After connecting without tor (see #963), the backend connected and everything worked as expected.

If there's additional debug info I can provide please let me know (and ideally explain how to do that), I'm willing to do my best to help debug this issue :)

**Comment by RiccardoMasutti** [comment]
This is the documentation repo. Please report it via https://github.com/zkSNACKs/WalletWasabi/issues or https://www.reddit.com/r/WasabiWallet.
