### ISSUE TITLE
Docs 1.0 is awesome but I'm looking forward to participate on creating 2.0!

### ISSUE THREAD

**Issue by BTCparadigm** [zkSNACKs/WasabiDoc#985]
You guys have done magnificent job creating and maintaining the Docs! I remember reading it though maybe 2 years ago, when I barely understood what's going on, but now that I'm doing it again, I've been pleasantly surprised how much awesome in-depth knowledge it actually contains.

But I do think there is still a lot to improve.
There's also a lot of things we should update, even though many things will get obsoleted with 2.0 Docs.
I think the current font and structure is a bit confusing and it takes a while to get used to it.
 
Should we schedule a call about how to proceed with creating WW2 documentation?
How about on Friday 16.4. at 14:00 CET?
Or maybe just bounce around some ideas in this thread?

**Comment by RiccardoMasutti** [comment]
WWII docs needs a complete restructuring. We can use v1 content for general topics but technical stuff should be done from scratch

**Comment by BTCparadigm** [comment]
[Docs 2.0](https://github.com/zkSNACKs/WasabiDoc2)!
