### ISSUE TITLE
[Request] State a recommended version for which version of Node.Js for building the docs locally

### ISSUE THREAD

**Issue by benthecarman** [zkSNACKs/WasabiDoc#99]
State a recommended version for which version of Node.Js for building the docs locally

**Comment by MaxHillebrand** [comment]
@dennisreimann do you know the minimum necessary version?

**Comment by dennisreimann** [comment]
In order to build the website locally, you'll need [Node.js](https://nodejs.org/) >= 10.16 (or basically the latest LTS version).

I have added this info to the README and we are now also ensuring it via a check in the npm scripts.
