### ISSUE TITLE
RPC method to delete wallet?

### ISSUE THREAD

**Issue by GiganteX** [zkSNACKs/WasabiDoc#990]
I can't find a method to delete a wallet, only to create? Could you implement that method?

**Comment by RiccardoMasutti** [comment]
Please post requests related to the software in the right repo: https://github.com/zkSNACKs/WalletWasabi/discussions
This is for documentation

**Comment by GiganteX** [comment]
Ah I see. Sorry.
The reason I posted it here was that when I'm on the RPC docs page:
https://docs.wasabiwallet.io/using-wasabi/RPC.html
the github button on top goes to this repo... which makes sense but also easy to misunderstand...
