### ISSUE TITLE
What happened to my transaction?

### ISSUE THREAD

**Issue by GiganteX** [zkSNACKs/WasabiDoc#991]
I tried to transfer some money from my Electrum wallet to my Wasabi wallet.

I had gotten 0.0005 BTC previously, spent about a tenth of that.. and then sent the remainder to my Wasabi wallet.

I sent the money, saw the transaction in Wasabi... it had 4 confirmations when I wanted to take a closer look at it
so I doubleclicked it.. or maybe rightclicked it to see if there was a context menu, not sure... but then it was... gone. 
Just gone from the History.

Maybe I cancelled it?? But then, where's the money? Balance is 0 in both wallets...

What happened??

Here's the transaction:
https://www.blockchain.com/btc/address/bc1q6y7x29jrtwaenk7h4df83v2j3yzgq4cve0lyl4

**Comment by GiganteX** [comment]
Could I have somehow removed the receive-address from the wallet?

**Comment by yahiheb** [comment]
Check the [logs file](https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#where-can-i-find-the-logs) and tell us if you see any erros there.

Btw this is the documentation repository and you shouldn't be asking for support here.
Go to the main repository https://github.com/zkSNACKs/WalletWasabi and open a support discussion there: https://github.com/zkSNACKs/WalletWasabi/discussions/categories/support

**Comment by GiganteX** [comment]
I can just find this that is related....

```
2021-05-08 12:07:48 INFO	Global (615)	Transaction Notification (Success): Received Replaceable Transaction - 0.00044672 BTC - f1ba040593b524f939b9a582790fd14dcf60fb7f73669a6daeb9aba05b8a24cb
2021-05-08 12:52:05 INFO	Global (615)	Transaction Notification (Information): Receive Confirmed - 0.00044672 BTC - f1ba040593b524f939b9a582790fd14dcf60fb7f73669a6daeb9aba05b8a24cb

```

"you shouldn't be asking for support here."

I'm thinking it's a bug... Because I clicked something (maybe?) my money is lost in the void...

**Comment by GiganteX** [comment]
No. You can delete this entire issue.

i just found the money. I was looking in the wrong wallet.

I am sorry... User error....
